### ISSUE TITLE
Need to set preprocessor macro LOGGING when logging is detected in the C library

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#100]
We need to set preprocessor macro LOGGING when logging is detected in the C library. Otherwise nf_set_log_level() is not included in netcdff.a.

The configure.ac already detects logging, we just need to set LOGGING for the subsequent build.

**Comment by zerothi** [comment]
Isn't this related to #26?

**Comment by edhartnett** [comment]
@zerothi Correct! Thanks for noticing. I've added a comment to #26 and will close this issue.

**Comment by zerothi** [comment]
Ok, ;)
