### ISSUE TITLE
Interface for nc_def_var_filter required

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-fortran#104]
It would be great to get this into our next release.

**Comment by WardF** [comment]
Taking a stab at this myself but if @piqueen314 or @DennisHeimbigner want to jump in and add the interface for the next release, that will be great.  Either way, I'll probably ask for one of the two to at least check my work.

**Comment by DennisHeimbigner** [comment]
I hope we are not working in parallel. I added nc_def_var_filter and nc_inq_var_filter
to the code: f 2003 only, no f77. I still need to add test cases.

**Comment by WardF** [comment]
I doubt very much we are, you have already made more progress than I. I will leave it to you and I will poke around as a learning experience.

**Comment by edhartnett** [comment]
@DennisHeimbigner unfortunately (or not) all the models I'm familiar with use the netCDF F77 API, not the F90 API. Most importantly, NCAR's WRF model uses the F77 API.

Or did you mean your function would only work with F2000 compilers? In that case, no problem. No one is stuck with F77 compilers any more.

**Comment by DennisHeimbigner** [comment]
I meant that I did not plan to insert the filter stuff
into the code in netcdf-fortran/libsrc.

**Comment by DennisHeimbigner** [comment]
BTW Ward, did this request originate with some external person?

**Comment by WardF** [comment]
Yes, there was a post about it on the NetCDF mailing list (I believe). I am on the road in Wyoming but will look it up when we stop.
