### ISSUE TITLE
tag a micro release now and move the 4.4.5 milestone to 4.4.6?

### ISSUE THREAD

**Issue by beckermr** [Unidata/netcdf-fortran#107]
Hi friends!

Over at conda-forge, we are in the process of rebuilding the full stack of packages for the latest Anaconda compilers. We are now blocked (https://github.com/conda-forge/netcdf-fortran-feedstock/pull/28) on the bug reported in #106, which from reading that issue has a patch on master. 

Would you all be able to tag a micro release now on master with the bug fix and then push the remaining issues on 4.4.5 to 4.4.6? This would help us tremendously!

Cheers!
Matt

@WardF @conda-forge/netcdf-fortran for viz

**Comment by beckermr** [comment]
Friendly bump on this issue! If y'all don't want to cut a new release, help finding the right commits to form a patch would be much appreciated!

**Comment by WardF** [comment]
Hi @beckermr I will see what I can do in the next day or so! Sorry for the delay, I've been traveling due to the holidays.

**Comment by beckermr** [comment]
Any updates on this issue @WardF?

**Comment by WardF** [comment]
Working on the tag now, should have the micro release out by end of day, barring any issues. I'm not sure if it still necessary with your other work fixing things, but it will be easy enough to do now that I've cleared my plate of some other issues.

**Comment by beckermr** [comment]
Thank you! Yeah I’d rather not maintain the patch so the release will be awesome!

**Comment by WardF** [comment]
[v4.4.5](https://github.com/Unidata/netcdf-fortran/releases/tag/v4.4.5) is live, although not announced yet; I'll need to upload the documentation and some internal files in the morning, at which point I'll make the formal announcement.  Thanks for your patience, sorry for making you wait!

**Comment by beckermr** [comment]
Huzzah! Thank you sooooo much!
