### ISSUE TITLE
CMake build does not provide pkg-config file nor man3 page

### ISSUE THREAD

**Issue by ArchangeGabriel** [Unidata/netcdf-fortran#108]
Missing files in CMake build vs autotools one:
```
usr/lib/pkgconfig/netcdf-fortran.pc
usr/share/man/man3/netcdf_fortran.3.gz
```

**Comment by WardF** [comment]
Thanks for pointing this out; I’ll fix!

**Comment by luzpaz** [comment]
Probably should be added to next release?

**Comment by WardF** [comment]
I will get this in.  Working to put together releases for the C, Fortran and C++ packages in short order, so rushing around a bit :).

**Comment by ArchangeGabriel** [comment]
This wasn’t fixed in 4.5 though.

**Comment by ArchangeGabriel** [comment]
Actually the CMake build does not work at all:
```
CMake Error at nf03_test4/CMakeLists.txt:88 (ADD_EXECUTABLE):
  Cannot find source file:

    tst_flarge.f90

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at nf03_test4/CMakeLists.txt:88 (ADD_EXECUTABLE):
  No SOURCES given to target: tst_flarge


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by WardF** [comment]
Interesting, as this is not happening on my local cmake install.  Let me take a look and see if I can sort it out.

**Comment by WardF** [comment]
Ok, I've sorted it out, and will be releasing `4.5.1` shortly to address this. Oops!

**Comment by ArchangeGabriel** [comment]
Still no luck for me, opening a new issue with more details.

**Comment by WardF** [comment]
This is peculiar, where are you grabbing the tar file from? Just to make sure I have the same source you do.  I was very particular to test the dist file sources with cmake, given the nature of the issue with 4.5.0.  Let me take another look, how are you invoking cmake?

**Comment by ArchangeGabriel** [comment]
The other thread (#198) partially answer that, but just for the record I use the GitHub tarball (e.g. https://github.com/Unidata/netcdf-fortran/archive/v4.5.1.tar.gz for this release).
