### ISSUE TITLE
make -j builds fail in nf_test

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#112]
Something in the nf_test test run doesn't work for parallel builds. I will take a look...

**Comment by edhartnett** [comment]
OK, here's some more details. When attempting this I encountered this problem:

`CPPFLAGS=-I/usr/local/netcdf-c-4.6.3_hdf5-1.10.5_mpich-3.2/include LDFLAGS=-L/usr/local/netcdf-c-4.6.3_hdf5-1.10.5_mpich-3.2/lib FC=mpifort FCFLAGS=-g ./configure --prefix=/usr/local/netcdf-fortran-4.4.5_c_4.6.3_mpich-3.2 --enable-parallel-tests && make -j check `

A subsequent make check worked. I don't have time to track this down at the moment but here was the failure:

```
PASS: run_f90_par_test.sh
../test-driver: line 107: 29424 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: nf_test

```

So is nf_test using a file from another test? Or is another test using and then deleting a file that nf_test needs?

**Comment by WardF** [comment]
It may well have a dependency; these were rife before the efforts to parallelize the builds was made in C, and I'm not surprised there may be some here in Fortran. I'll take a look and try to detangle.

**Comment by edhartnett** [comment]
OK, but wait! I just remembered that nf_test/Makefile.am has this:

# Parallel builds don't currently work in this directory.
.NOTPARALLEL:

So it's not even attempting parallel makes in this directory. Therefore my problem was probably just an artifact of a previous build gone wrong.

Furthermore, I just checked my CI system and I am successfully doing a bunch of make -j check builds.

I will wipe those workspaces and relaunch. If they succeed I will close this ticket.

**Comment by edhartnett** [comment]
I cannot reproduce this problem so I think it was just an artifact of build crud left over from a previous build.
