### ISSUE TITLE
in nf_test unneeded file fills.nc copied from ref_fills.nc

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#129]
When the fortran and C build were together, some of the fortran tests used to use ncdump to generate a test file (fills.nc) from ref_fills.cdl. When the builds were separated, the ref_fill.cdl was replaced with ref_fill.nc, and the script was change to just copy that to fills.nc with the test script create_fills.sh.

Not sure why this roundabout method was adopted. Instead, we should just read ref_fills.nc directly, The create_fillls.sh script is not needed, nor is temporary file fills.nc.

I will fix, and simplify the build.

**Comment by edhartnett** [comment]
OK, I have since remembered that I did this because I didn't know about the autoconf macro AC_CONFIG_LINKS which handles copying the reference file into the (potentially different) build directory.

**Comment by WardF** [comment]
Was a big lightbulb moment when I found `AC_CONFIG_LINKS` over in the C project, for some hdf5 tests I had been propagating all over the place manually.  Thanks for your help with this.

**Comment by edhartnett** [comment]
Well autotools are a learning experience, that's for sure. It's great to have a chance to bring these automake and autoconf files up to date with my current understanding of autotools. ;-)
