### ISSUE TITLE
Fortran configure does not correctly determine parallel I/O status for netcdf-c-4.6.1

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#133]
Looks like at some point someone added NC_HAS_PARALLEL4 to netcdf_meta.h, and that's what the netcdf-fortran configure file is looking for.

But in 4.6.1 there was NC_HAS_PARALLEL but not NC_HAS_PARALLEL4. So netcdf-fortran does not correctly detect whether 4.6.1 has parallel or not.

I will fix.

**Comment by wkliao** [comment]
It is I added NC_HAS_PARALLEL4.
NC_HAS_PARALLEL4 indicates whether parallel HDF5 is enabled.

In NetCDF-C 4.6.1 and prior, NC_HAS_PARALLEL has been used to indicate
at least one parallel driver is enabled (parallel HDF5 or PnetCDF), but
there is no unique constant for parallel HDF5 driver.

**Comment by edhartnett** [comment]
Yes, I have added code such that if NC_HAS_PARALLEL is true, and NC_HAS_PNETCDF is false, then the configure.ac correctly decides that NC_HAS_PARALLEL4 should be set.

**Comment by edhartnett** [comment]
Now that I think about it further, I realize I am still not done here. My current solution (up in PR) is an improvement, but still leaves one case handled incorrectly - what if both pnetcdf and netcdf-4 parallel I/O are enabled? In this case, the fortran configure will miss the netCDF-4 parallel I/O features.

This can be fixed by looking for function nc_open_par() instead of checking netcdf_meta.h for flags. The presence/absence of nc_open_par() conclusively indicates whether netcdf-4 parallel I enabled.

So I will leave this issue open and circle around again to make this better after my current PR gets merged.

**Comment by wkliao** [comment]
If netCDF-C is configured with both parallel NetCDF4 and PnetCDF enabled, then all NC_HAS_PNETCDF, NC_HAS_PARALLEL4, and NC_HAS_PARALLEL will be defined as 1s.

Checking nc_open_par is not sufficient, as both parallel drivers are called through nc_open_par. Thus, checking the above 3 constants in file netcdf-meta.h may be still necessary.

Another way to check is to use nc-config with command-line options --has-parallel4, --has-parallel, and --has-pnetcdf.

**Comment by edhartnett** [comment]
@wkliao thanks for pointing that out wrt nc_open_par(). Of course you are correct, it will be in the library if pnetcdf or netCDF-4 parallel I/O is available.

In most recent releases we continue to check netcdf_meta.h and use NC_HAS_PARALLEL4. The issue is what to do for releases of netCDF-c that don't have NC_HAS_PARALLAL4.

Perhaps we have reached the best state available with old releases. The 4.6.2 and later releases work fine. With my current PRs, the netcdf-fortran build will work in most cases with earlier releases, but not with earlier releases that have both netCDF-4 and pnetcdf parallel I/O. 

So if anyone encounters these problems with earlier C library releases, the answer is to upgrade to 4.6.2.
