### ISSUE TITLE
Incorrect paths in nf-config

### ISSUE THREAD

**Issue by aerorahul** [Unidata/netcdf-fortran#136]
https://github.com/Unidata/netcdf-fortran/blob/3df5a49d68dfe3baab6ae31e3774f4d3cbd602dc/nf-config.in#L7-L9

These should be:
```
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@
```

**Comment by aerorahul** [comment]
Connect issue with pr #137

**Comment by WardF** [comment]
Fixed by pull request. Thanks!
