### ISSUE TITLE
cmake build missing netcdf.inc

### ISSUE THREAD

**Issue by Roy-KC** [Unidata/netcdf-fortran#138]
Fresh clone, using "cmake" without "configure", fails on some of the f77 tests because "netcdf.inc" is not found.

If I run configure and copy the netcdf.inc file into the build directory, "make test" succeeds.

MacOS High Sierra 10.13.6
Xcode 9.4.1
cmake-gui 3.13.4
ifort (IFORT) 19.0.2.184 20190117

**Comment by WardF** [comment]
Thanks! I will take a look and get this corrected so that cmake-based builds work properly.

**Comment by Roy-KC** [comment]
I cloned again this afternoon, used cmake without configure, and "make test" did not generate any errors.

**Comment by WardF** [comment]
Excellent, thank you for the follow up, I was struggling to recreate it on my end.
