### ISSUE TITLE
Mac OSX configure with ifort does not create shared lib

### ISSUE THREAD

**Issue by Roy-KC** [Unidata/netcdf-fortran#139]
The test for creating a shared lib fails, so a "configure" build does not produce a shared library.

Mac OSX High Sierra 10.13.6
ifort (IFORT) 19.0.2.184 20190117

**Comment by edhartnett** [comment]
If I understand you correctly, the configure script could not successfully create a shared library, so the netcdf-fortran build does not produce one.

If so, you need to examine config.log and fix whatever it is which is preventing shared library builds from working. This is not a netcdf bug - if configure can't build shared libraries, then certainly netcdf-fortran will not be able to.

**Comment by Roy-KC** [comment]
The configure script does fail the shared lib test.  Unfortunately, there is no useful information in the log file.  I may try replacing LD with ifort.  I do understand this is a configuration failure.

**Comment by edhartnett** [comment]
Can you,post the config.log section where the failure is?

**Comment by Roy-KC** [comment]
[config.log](https://github.com/Unidata/netcdf-fortran/files/2919841/config.log)

**Comment by edhartnett** [comment]
According to this: https://stackoverflow.com/questions/14368627/libtool-claims-it-does-not-support-shared-libraries-during-cross-compilation

the problem may be in how you specify the target architecture. Try --host=x86_64-none-linux.

**Comment by Roy-KC** [comment]
Thank you for going the extra mile.  I was unsuccessful unearthing the post you listed.  I am able to get a shared library if I do not specify a host and allow config.guess to figure it out.  Sorry to waste your time.
