### ISSUE TITLE
CDF5 format constants are not defined in the F90 API

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#172]
The constants NF_CDF5 and NF_FORMAT_CDF5 are missing from module_netcdf_nf_data.F90. I will add them.

**Comment by WardF** [comment]
If you get a PR for this up in the next day or so it will go into the release I'll push out this week.  Thanks!

**Comment by edhartnett** [comment]
OK will do!

**Comment by edhartnett** [comment]
We also need to add a CDF5 test for the F90 API...
