### ISSUE TITLE
Fails to build against libnetcdf built without netcdf4 support.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-fortran#200]
Will update with details, getting issue opened at moment. Fails to link against libnetcdf built without netCDF4 support.  Needs to have configuration-time function checks and fenceposts added.

**Comment by edhartnett** [comment]
Well crap, I'm not testing this but I guess I better. ;-)

Is this the cmake or autotools build? Or both?

**Comment by WardF** [comment]
It's both, the tests are failing due to undefined references to:

* `nc_get_chunk_cache_ints`
* `nc_get_var_chunk_cache_ints`
* `nc_inq_var_chunking_ints`
* `nc_set_var_chunk_cache_ints`
* `nc_def_var_chunking_ints`
* `nc_set_chunk_cache_ints`

Still trying to nail down where/why this is happening; I'll also get to the C PR ASAP, but need to get a 4.7.2 release out to fix this; there are a number of packages which apparently instruct their users to compile netCDF_C without netCDF4 support, and we're fielding a lot of support requests due to this issue.

**Comment by WardF** [comment]
`configure.ac` was using `nc_def_opaque` to determine if `libnetcdf.so` was built with netCDF-4 support.  This is now true even if netCDF-4 support isn't actually active.  As a result, `USE_NETCDF4` was flagged as `TRUE` even when it should haven't been. Doing some digging now and will follow up.
