### ISSUE TITLE
I would like to change all code to *.F90 and be able to use pre-processor in fortran code too. 

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-fortran#214]
In olden times there was no distinction between .f90 and .F90 files. But these days, .F90 is preferred and there is a distinction.

The distinction is that all fortran compilers will now run .F90 files through the pre-processor. This is the new normal for Fortran. 

We don't use the pre-processor in our fortran code, but we should follow the convention of using .F90. Some of our files are F90 and some f90. We can change the .f90 to .F90 and be consistent and in conformance with modern fortran practice.

**Comment by ArchangeGabriel** [comment]
In my understanding, the good practice is that .F90 should only be used when the file must go through the pre-processor, while .f90 should be used otherwise.

**Comment by edwardhartnett** [comment]
Well that's true and I was waiting for an example before I reply, but I would like all Fortran code to go through the pre-processor, including test codes, so that's why I want to switch to .F90. ;-)

For an example of why see #254 

GFDL and NOAA now distribute a lot or all of their fortran code as .F90, and count on the pre-processor, and that seems to work OK. All the Fortran compilers support that these days.

**Comment by edwardhartnett** [comment]
See #355 for further discussion...
