### ISSUE TITLE
Build fails with NAG compiler 6.2

### ISSUE THREAD

**Issue by tstrempel** [Unidata/netcdf-fortran#218]
* 4.4.4 and 4.5.2
* CentOS7, NAG 6.2 Build 6223, GCC 7.3.0, netCDF 4.6.1 (no MPI), HDF 1.10.2 (no MPI)
* I think https://github.com/Unidata/netcdf-fortran/issues/212 has the same issue.
* Reproducible via `export FC=nagfor && ./configure && make`

Error:

nagfor -I. -g -c -o module_netcdf4_f03.o  module_netcdf4_f03.f90
NAG Fortran Compiler Release 6.2(Chiyoda) Build 6223
[NAG Fortran Compiler normal termination]
nagfor -I. -g -c -o netcdf4.o  netcdf4.f90
NAG Fortran Compiler Release 6.2(Chiyoda) Build 6223
Warning: netcdf_text_variables.f90, line 19: Unused dummy variable MAP
Warning: netcdf_text_variables.f90, line 39: Unused dummy variable MAP
Warning: netcdf4_func.f90, line 761: Unused dummy variable LENGTH
Warning: netcdf4_func.f90, line 781: Unused dummy variable MAP
Warning: netcdf4_func.f90, line 801: Unused dummy variable MAP
Warning: netcdf4.f90, line 67: Unused external reference NF_FREE_STRING
Warning: netcdf4.f90, line 67: Unused external reference NF_FREE_VLENS
Warning: netcdf4.f90, line 67: Unused external reference NF_GET_VAR1_TEXT
Warning: netcdf4.f90, line 67: Unused external reference NF_GET_VARA_TEXT
Warning: netcdf4.f90, line 67: Unused external reference NF_GET_VAR_INT64
Warning: netcdf4.f90, line 67: Unused external reference NF_INQ_VAR_SZIP
Warning: netcdf4.f90, line 67: Unused external reference NF_PUT_VAR1_TEXT
Warning: netcdf4.f90, line 67: Unused external reference NF_PUT_VARA_TEXT
Warning: netcdf4.f90, line 67: Unused external reference NF_PUT_VAR_INT64
Warning: netcdf4.f90, line 67: Unused external reference NF_PUT_VLEN_ELEMENT
Error: netcdf4_func.f90, line 640: Inconsistent data type INTEGER(int16) (previously INTEGER(int8)) for argument 4 in reference to NF_DEF_VAR_FILL
Error: netcdf4_func.f90, line 650: Inconsistent data type INTEGER (previously INTEGER(int8)) for argument 4 in reference to NF_DEF_VAR_FILL
Error: netcdf4_func.f90, line 660: Inconsistent data type INTEGER(int64) (previously INTEGER(int8)) for argument 4 in reference to NF_DEF_VAR_FILL
Error: netcdf4_func.f90, line 670: Inconsistent data type REAL (previously INTEGER(int8)) for argument 4 in reference to NF_DEF_VAR_FILL
Error: netcdf4_func.f90, line 680: Inconsistent data type DOUBLE PRECISION (previously INTEGER(int8)) for argument 4 in reference to NF_DEF_VAR_FILL
Error: netcdf4_func.f90, line 700: Inconsistent data type INTEGER(int16) (previously INTEGER(int8)) for argument 4 in reference to NF_INQ_VAR_FILL
Error: netcdf4_func.f90, line 710: Inconsistent data type INTEGER (previously INTEGER(int8)) for argument 4 in reference to NF_INQ_VAR_FILL
Error: netcdf4_func.f90, line 720: Inconsistent data type INTEGER(int64) (previously INTEGER(int8)) for argument 4 in reference to NF_INQ_VAR_FILL
Error: netcdf4_func.f90, line 730: Inconsistent data type REAL (previously INTEGER(int8)) for argument 4 in reference to NF_INQ_VAR_FILL
Error: netcdf4_func.f90, line 740: Inconsistent data type DOUBLE PRECISION (previously INTEGER(int8)) for argument 4 in reference to NF_INQ_VAR_FILL
[NAG Fortran Compiler error termination, 10 errors, 15 warnings]
make[1]: *** [netcdf4.o] Error 2
make[1]: Leaving directory `/gpfs0/home/admtost/builds/netcdf-fortran-4.5.2/fortran'
make: *** [all-recursive] Error 1

**Comment by tstrempel** [comment]
For everyone who has the same problem, this is how I solved it via the `-mismatch_all` flag:

```
wget https://github.com/Unidata/netcdf-fortran/archive/v4.4.5.tar.gz
tar xf v4.4.5.tar.gz
cd netcdf-fortran-4.4.5
module load GCC/7.3.0-2.30 HDF5/1.10.2-nompi netCDF/4.6.1-nompi NAGfor/6.2.14
export FC=nagfor
export FCFLAGS="-mismatch_all"
./configure --prefix=/some/directory
make
make install
```

I had to use v4.4.5, because it was the only release I tested without linking issues.

**Comment by WardF** [comment]
Thanks, this is very helpful.  We are working on a release right now, and I will see what we can do about getting the NAG compiler working again.
