### ISSUE TITLE
szip tests not run in cmake build, but should be

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-fortran#223]
Recently I added test program nc_test4/ftst_var_szip.F, which is run in autotools builds if netcdf-c was built with szip write ability.

However, I neglected to add this test to the cmake build.

**Comment by edwardhartnett** [comment]
@WardF I could use some help here. I need to check the value of a setting in netcdf_meta.h from the netcdf-fortran CMake build. But I don't know how...

**Comment by WardF** [comment]
Let me dig up the example

**Comment by WardF** [comment]
Similar to `AC_COMPILE_IFELSE()` in autotools, you can use `CHECK_C_SOURCE_COMPILES` in cmake.  The following example is from line `116` in the netCDF-C `CMakeLists.txt`:

````
      CHECK_C_SOURCE_COMPILES("int main() {return 0;}" ${M_RESULT})
````
It requires including the CMake `CheckCSourceCompiles` module at the head of the file via the addition of

    INCLUDE(CheckCSourceCompiles)`

I assume you can use a small C program with an include to netcdf_meta.h similar to the method used in `configure.ac`. Does this help?

**Comment by edwardhartnett** [comment]
Thanks, I'll give it a try and we'll see how it goes! ;-)
