### ISSUE TITLE
Official advice on combining cmode flags

### ISSUE THREAD

**Issue by mathomp4** [Unidata/netcdf-fortran#241]
All,

This is a simple thing and I think I know the "correct" answer, but I wanted to get the Official Word™. Namely,  I saw this in our code recently:
```fortran
      status = nf90_create(file, NF90_NOCLOBBER + NF90_HDF5, this%ncid)	
```
and thought, oh, that should be:
```fortran
      status = nf90_create(file, NF90_NOCLOBBER + NF90_NETCDF4, this%ncid)	
```
because `NF90_HDF5` is deprecated. But then I realized, wait, the examples with netCDF-Fortran would say we should do:
```fortran
      status = nf90_create(file, IOR(NF90_NOCLOBBER, NF90_NETCDF4), this%ncid)	
```
Amazingly, all three of these work I think because the constants are positive. I'm pretty sure if any were negative then A+B != IOR(A,B).

So I took a look at the [NF90_CREATE documentation](https://github.com/Unidata/netcdf-fortran/blob/master/docs/netcdf-f90-sec2-datasets.md#25-nf90_create-f90-nf90_create) and didn't see any official advice. 

Assuming ```IOR()``` is the correct way to do this, would it be possible for someone put a line or two in that section (or somewhere generic?) saying if you want more than one flag to use ```IOR()``` to combine them?

**Comment by zerothi** [comment]
The problem comes when you *accidentally* do two additions of the same type, then you will use a different flag.

```fortran
NF90_NOCLOBBER + NF90_NETCDF4 + NF90_NETCDF4 != IOR(IOR(NF90_NOCLOBBER, NF90_NETCDF4), NF90_NETCDF4)
```
So your last statement (`A+B != IOR(A, B)`) only holds in corner cases.

**Comment by zerothi** [comment]
I.e. *always* use nested `IOR` statements! :)

```fortran
mode = NF90_CLOBBER
mode = IOR(mode, NF90_NETCDF4)
mode = IOR(mode, ...)
mode = IOR(mode, ...)
mode = IOR(mode, ...)
```
