### ISSUE TITLE
CMake Build INCLUDEDIR not set properly

### ISSUE THREAD

**Issue by gitporst** [Unidata/netcdf-fortran#252]
When using the CMake build, the `Fortran_INSTALL_MODDIR` variable is set to a Boolean value and later on used to determine a path (in `fortran/CMakeLists.txt`):
```
INSTALL(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/
        DESTINATION "${Fortran_INSTALL_MODDIR}"
        FILES_MATCHING PATTERN "*.mod" PATTERN "netcdf.inc"
        )
``` 

So I am wondering if we should replace in `CMakeLists.txt.`:
```
OPTION(Fortran_INSTALL_MODDIR "Fortran module install directory" "${CMAKE_INSTALL_INCLUDEDIR}")
```
by
```
SET(Fortran_INSTALL_MODDIR "${CMAKE_INSTALL_INCLUDEDIR}" CACHE STRING "Fortran module install directory")
```

Just for my understanding, why is there a variable `Fortran_INSTALL_MODDIR` that is used instead of `CMAKE_INSTALL_INCLUDEDIR`?

**Comment by WardF** [comment]
Interesting question; it might be an artifact from when we initially added cmake support for Fortran.  I'll take a look at this and make the appropriate changes, thanks!
