### ISSUE TITLE
Logging in fortran

### ISSUE THREAD

**Issue by zerothi** [Unidata/netcdf-fortran#26]
The `nf_set_log_level` routine will only be created if the `LOGGING` preprocessor variable is present.

However, this is not automatically generated by the C-interface by compiling with `--enable-logging`.

Procedure:

compile netcdf-c:

``` bash
mkdir build-tmp ; cd build-tmp
../configure --enable-logging
<make etc>
```

After completion the netcdf.h file contains this:

``` c
#ifdef LOGGING

/* Set the log level. 0 shows only errors, 1 only major messages,
 * etc., to 5, which shows way too much information. */
EXTERNL int
nc_set_log_level(int new_level);

/* Use this to turn off logging by calling
   nc_log_level(NC_TURN_OFF_LOGGING) */
#define NC_TURN_OFF_LOGGING (-1)

#else /* not LOGGING */

#define nc_set_log_level(e)

#endif /* LOGGING */
```

But no `#define LOGGING 1`.  
If you then compile netcdf-fortran on-top of the c-library you will not get the `nf_set_log_level` command unless you manually add `-DLOGGING` to the CPPFLAGS.

I am slightly unsure what the intent was of the various routines. But either the `LOGGING` variable should be present in the `netcdf.h` file or there should be a configure flag for enabling logging (`--enable-logging`) in the fortran version.

I have filed the issue here due to me being unsure where you consider the error to be located.

**Comment by WardF** [comment]
Thanks for submitting issue; sorry for the delayed response, I'll take a look at it.

**Comment by edhartnett** [comment]
OK, this will go away when we make nc_set_log_level() always available. See https://github.com/Unidata/netcdf-c/issues/643.

Until then the workaround is to add -DLOGGING to the CPPFLAGS, as you have suggested.

**Comment by edhartnett** [comment]
I thought this would go away with always defining nc_set_log_level() but I was mistaken. In addition we must set the LOGGING macro is configure.ac when we determine the nc_set_log_level() is present in the C library.

**Comment by edhartnett** [comment]
Well I am not sure what happened, I thought I had fixed this, but I am finding that even with LOGGING defined, the latest fortran release does not seem to contain nf_set_log_level().

**Comment by zerothi** [comment]
Great, thanks for checking this!
