### ISSUE TITLE
./mk  & ./rn error

### ISSUE THREAD

**Issue by Alaaibrahim96** [Unidata/netcdf-fortran#279]
Hello,

### I ran ./mk in macOS (version 10.13.6)& gfortran version: GNU Fortran (GCC) 9.2.0 . and I got this error:

gfortran -Wno-uninitialized -fno-range-check -fmax-errors=7  -fprotect-parens -fno-sign-zero -fbacktrace -ggdb -finit-real=snan -fopenmp -fbounds-check -Wuninitialized -Warray-bounds -ggdb -ffree-form -ffree-line-length-none -x f95-cpp-input -I/Users/macos/Documents/mesa-r12778/include -c ../src/run_star_extras.f
../src/run_star_extras.f:28:10:

   28 |       use crlibm_lib
      |          1
Fatal Error: Cannot open module file 'crlibm_lib.mod' for reading at (1): No such file or directory
compilation terminated.
make: *** [run_star_extras.o] Error 1

FAILED

### Another issue: I ran ./rn and I got this error:

svn: E155007: '/Users/macos/Documents/mesa-r12778' is not a working copy
Fri Aug 28 17:41:26 EEST 2020
 version_number 12778
 read inlist_control

Failed while trying to read control namelist file: inlist_control
Perhaps the following runtime error message will help you find the problem.

At line 657 of file ../private/ctrls_io.f90
Fortran runtime error: Cannot match namelist object name photostep

Error termination. Backtrace:
#0  0x13cb059ed
#1  0x13cb06675
#2  0x13cb0709b
#3  0x13cd13e95
#4  0x13cd1cbf7
#5  0x13cd1ce18
#6  0x13cd1cf67
#7  0x1047566fb
#8  0x1047439d4
#9  0x1047568f1
#10  0x104756965
#11  0x104af0804
#12  0x104b09e1d
#13  0x104b0aba7
#14  0x1046d1bfa
#15  0x1046d1cad
#16  0x1046d1cf1

Could you please help me?

**Comment by WardF** [comment]
I'm afraid I don't know what either `mk` or `rn` are, as they are not part of the netCDF-Fortran distribution. Can you provide additional information?

**Comment by Alaaibrahim96** [comment]
I use these two files (./mk & ./rn files) to do some calculations from an open source website.

This is the ./mk file: 

#!/bin/bash
  
function check_okay {
        if [ $? -ne 0 ]
        then
                echo
                echo "FAILED"
                echo
                exit 1
        fi
}

cd make; make; check_okay 
I am trying to do ./mk command but it didn't worked 

Also for the run file:

#!/bin/bash
  
if [ ! -z "${MESA_DIR}" ]; then
  svn info $MESA_DIR > .svninfo
  grep "Revision" .svninfo
fi

rm -f restart_photo
date;./star;date 

Is this enough? I don't know exactly how to give more information.

**Comment by WardF** [comment]
I don't really know what these scripts do, or if they are part of some other package, but any relationship to netcdf-fortran is not obvious to me.  The inclusion of `MESA_DIR` makes me suspect that this is part of some other package that perhaps relies on netcdf-fortran? Can you tell me more about where the files come from, or what project they are associated with?

**Comment by Alaaibrahim96** [comment]
Thank you for your attention

This is the open source website: 
http://mesa.sourceforge.net/

and I downloaded the files from this link: https://zenodo.org/record/3372833#.X0ka1BczbaY

**Comment by WardF** [comment]
Ok, this doesn't appear to be an issue with netcdf-fortran; my advice would be to contact the mesa development team and ask them how to proceed.  I'm sorry I don't have any more immediately actionable advice, but the errors you are reporting from their scripts do not indicate a problem related to netcdf-fortran in any way that I can see.  Good luck!

**Comment by Alaaibrahim96** [comment]
Ok, I'll contact them
thank you so much
