### ISSUE TITLE
Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran

### ISSUE THREAD

**Issue by ZYWZong** [Unidata/netcdf-fortran#285]
Does anyone know what might be the cause of this error? How may I resolve this issue? Thanks in advance!

**Comment by ZYWZong** [comment]
Does anyone know what might be the cause of this error? How may I resolve this issue? Thanks in advance!

**Comment by WardF** [comment]
Can you describe where you're at in the process when this happens? Is this happening when you're trying to build netcdf fortran? Or when you're trying to link a project against it? Can you provide some more information regarding what you're doing when this error occurs?
