### ISSUE TITLE
automatic connect in figure

### ISSUE THREAD

**Issue by nemati456** [Unidata/netcdf-fortran#29]
hi!
I have a problem with tecplot
I want to plot 2 separate circule in one figure but.......
tecplot connect last node of first to first node of second circle automatically.
Its make problem for my other work
in the second figure this connect is between airfoil and circle
this is the code(or attached file)
with regad!

implicit none
integer::i,j
real::r1,teta,r2,r
real,dimension(0:361,2):: x, y
r1=2
r2=5

do j=1,2
teta=0
if(j==1)then
r=r1
j=1
else
r=r2
end if
do i=0,360
x(i,j)=rcos(teta)
y(i,j)=rsin(teta)
teta=3.1415/180+teta
!print*,i,teta,x(i,j)
end do
end do

OPEN(UNIT=10,FILE='RESULT circle.PLT')
WRITE(10,)'VARIABLES="X","Y"' 
WRITE(10,)'ZONE I=',361*2,'F=POINT'
do j=1,2

do i=0,360

WRITE(10,*)x(i,j),y(i,j)
END DO 
enddo

close(10)

end
![Uploading eliptic.jpg…]()
![Uploading export.jpg…]()

**Comment by WardF** [comment]
I'm not sure what tecplot is but since this is not related to NetCDF-fortran I'm closing the issue out. 

It looks like tecplot support may be found at http://www.tecplot.com

**Comment by nemati456** [comment]
thanks for answering but i canot found refrence that solve my problem 
thanks alot
