### ISSUE TITLE
swap of first and third dimension when reading and writing netcdf file

### ISSUE THREAD

**Issue by coiby** [Unidata/netcdf-fortran#30]
Hi Developers,

I find a weird thing in netcdf-fortran. I'm not sure if this is a bug.

I use netcdf-fortran on Ubuntu 14.04.
```
sudo apt-get install libnetcdf-dev libgdal1-dev
```
The versions are:
- libnetcdf-dev (= 1:4.1.3-7ubuntu2)
- libnetcdff5 (= 1:4.1.3-7ubuntu2)

Following the NetCDF Fortran 90 Interface docs, I get three dimensions size NX,NY,NZ through nf90_inquire_dimension, then I allocate an NXxNYxNZ array `idata` to read data values through NF90_GET_VAR.

    nf90_inquire_dimension(ncid,1,xname,NX)
    nf90_inquire_dimension(ncid,2,yname,NY)
    nf90_inquire_dimension(ncid,3,zname,NZ)
    nf90_get_var(ncid,varid,idata)

However, `idata` should have a NZxNYxNX dimension. There seems to be an exchange between Dimension 1 and 3.

For writing to netcdf, there's also such problem. Here's a program for testing.

```fotran
!compile and link: gfortran -g  -fbounds-check  ex.f90 -o ex -I /usr/include -lnetcdff
PROGRAM ex
    IMPLICIT NONE
    REAL(KIND=4), DIMENSION(:,:,:), ALLOCATABLE :: mydata, mydata2
    REAL(KIND=4), DIMENSION(:), ALLOCATABLE :: xpos, ypos, zpos
    REAL(KIND=4) :: x, y, z
    INTEGER(KIND=4) :: NX
    INTEGER(KIND=4) :: NY
    INTEGER(KIND=4) :: NZ
    INTEGER(KIND=4) :: J, K, L
    CHARACTER(LEN=50) :: outfile
    outfile = 'ex1.nc'
    NX = 360
    NY = 180
    NZ = 60
    ALLOCATE(mydata(NX,NY,NZ))
    ALLOCATE(mydata2(NX,NY,NZ))
    ALLOCATE(xpos(NX))
    ALLOCATE(ypos(NY))
    ALLOCATE(zpos(NZ))
    !Populate X, Y and Z grid locations
    x = 1
    DO J=1,NX
        xpos(J) = x
        x = x + 1.0
    ENDDO
    y = 1
    DO J=1,NY
        ypos(J) = y
        y = y + 1.0
    ENDDO
    z=1
    DO L=1,NZ
        zpos(L) = z
        z = z + 1.0
    ENDDO
    !make up some data
    DO J=1,NX
        x = xpos(J)
        DO K=1,NY
            y = ypos(K)
            DO L=1,NZ
               z = zpos(L)
               mydata(J,K,L) = x+y+z
               mydata2(J,K,L) = x*10000+y+z*0.0001
            ENDDO
        ENDDO
    ENDDO
    !write netCDF file
    CALL writegrid(outfile,xpos,ypos,zpos,mydata,mydata2,NX,NY,NZ)
END PROGRAM ex

!Check (ever so slightly modified from www.unidata.ucar.edu)
!:======================================================================
SUBROUTINE check(istatus)
    USE netcdf
    IMPLICIT NONE
    INTEGER, INTENT (IN) :: istatus
    IF (istatus /= nf90_noerr) THEN
        write(*,*) TRIM(ADJUSTL(nf90_strerror(istatus)))
    END IF
END SUBROUTINE check
!:======================================================================


!WRITEGRID - write a netCDF gridfile
!:=========================================================================
SUBROUTINE writegrid(outfile,xpos,ypos,zpos,idata,idata2,NX,NY,NZ)
    USE netcdf
    IMPLICIT NONE
    REAL(KIND=4), DIMENSION(NX), INTENT(IN) :: xpos
    REAL(KIND=4), DIMENSION(NY), INTENT(IN) :: ypos
    REAL(KIND=4), DIMENSION(NZ), INTENT(IN) :: zpos
    REAL(KIND=4), DIMENSION(NX,NY,NZ), INTENT(IN) :: idata
     REAL(KIND=4), DIMENSION(NX,NY,NZ), INTENT(IN) :: idata2
    INTEGER(KIND=4) :: ncid, x_dimid, y_dimid, z_dimid
    INTEGER(KIND=4) :: x_varid, y_varid, z_varid, varid, varid2
    INTEGER(KIND=4), DIMENSION(3) :: dimids
    INTEGER(KIND=4), INTENT(IN) :: NX, NY,NZ
    CHARACTER(LEN=50), INTENT(IN) :: outfile
    !Create the netCDF file.
    CALL check(nf90_create(outfile, NF90_CLOBBER, ncid))
    !Define the dimensions.
    CALL check(nf90_def_dim(ncid, "lon", NX, x_dimid))
    CALL check(nf90_def_dim(ncid, "lat", NY, y_dimid))
    CALL check(nf90_def_dim(ncid, "dep", NZ, z_dimid))
    !Define coordinate variables
    CALL check(nf90_def_var(ncid, "lon", NF90_REAL, x_dimid, x_varid))
    CALL check(nf90_def_var(ncid, "lat", NF90_REAL, y_dimid, y_varid))
    CALL check(nf90_def_var(ncid, "dep", NF90_REAL, z_dimid, z_varid))
    dimids = (/ x_dimid, y_dimid, z_dimid /)
    !Define variable
    CALL check(nf90_def_var(ncid, "Perturbations", NF90_FLOAT, dimids, varid))
    CALL check(nf90_def_var(ncid, "Pb2", NF90_FLOAT, dimids, varid2))
    CALL check(nf90_enddef(ncid)) !End Definitions
    !Write Data
    CALL check(nf90_put_var(ncid, x_varid, xpos))
    CALL check(nf90_put_var(ncid, y_varid, ypos))
    CALL check(nf90_put_var(ncid, z_varid, zpos))
    CALL check(nf90_put_var(ncid, varid, idata))
    CALL check(nf90_put_var(ncid, varid2, idata2))
    CALL check(nf90_close(ncid))
END SUBROUTINE writegrid
!:=========================================================================
```

Thank you!

**Comment by zerothi** [comment]
--

Kind regards Nick Papior
On 8 Sep 2015 15:07, "Coiby" <notifications@github.com> wrote:
>
> Hi Developers,
>
> I find a weird thing in netcdf-fortran. I'm not sure if this is a bug.
>
> I use netcdf-fortran on Ubuntu 14.04.
>
> sudo apt-get install libnetcdf-dev libgdal1-dev
>
> The versions are:
>
> libnetcdf-dev (= 1:4.1.3-7ubuntu2)
> libnetcdff5 (= 1:4.1.3-7ubuntu2)
>
> Following the NetCDF Fortran 90 Interface docs, I get three dimensions
size NX,NY,NZ through nf90_inquire_dimension, then I allocate an NXxNYxNZ
array idata to read data values through NF90_GET_VAR.
>
> nf90_inquire_dimension(ncid,1,xname,NX)
> nf90_inquire_dimension(ncid,2,yname,NY)
> nf90_inquire_dimension(ncid,3,zname,NZ)
> nf90_get_var(ncid,varid,idata)
>
> However, idata should have a NZxNYxNX dimension. There seems to be an
exchange between Dimension 1 and 3.
What do you mean by should? There is no bug, it behaves exactly as written
in the API.
Note that a change of indices between the appearance and the fortran code
is due to c vs fortran memory layout.
>
> For writing to netcdf, there's also such problem. Here's a program for
testing.
What is the problem? Please elaborate.
>
> !compile and link: gfortran -g  -fbounds-check  ex.f90 -o ex -I
/usr/include -lnetcdff
> PROGRAM ex
>     IMPLICIT NONE
>     REAL(KIND=4), DIMENSION(:,:,:), ALLOCATABLE :: mydata, mydata2
>     REAL(KIND=4), DIMENSION(:), ALLOCATABLE :: xpos, ypos, zpos
>     REAL(KIND=4) :: x, y, z
>     INTEGER(KIND=4) :: NX
>     INTEGER(KIND=4) :: NY
>     INTEGER(KIND=4) :: NZ
>     INTEGER(KIND=4) :: J, K, L
>     CHARACTER(LEN=50) :: outfile
>     outfile = 'ex1.nc'
>     NX = 360
>     NY = 180
>     NZ = 60
>     ALLOCATE(mydata(NX,NY,NZ))
>     ALLOCATE(mydata2(NX,NY,NZ))
>     ALLOCATE(xpos(NX))
>     ALLOCATE(ypos(NY))
>     ALLOCATE(zpos(NZ))
>     !Populate X, Y and Z grid locations
>     x = 1
>     DO J=1,NX
>         xpos(J) = x
>         x = x + 1.0
>     ENDDO
>     y = 1
>     DO J=1,NY
>         ypos(J) = y
>         y = y + 1.0
>     ENDDO
>     z=1
>     DO L=1,NZ
>         zpos(L) = z
>         z = z + 1.0
>     ENDDO
>     !make up some data
>     DO J=1,NX
>         x = xpos(J)
>         DO K=1,NY
>             y = ypos(K)
>             DO L=1,NZ
>                z = zpos(L)
>                mydata(J,K,L) = x+y+z
>                mydata2(J,K,L) = x*10000+y+z*0.0001
>             ENDDO
>         ENDDO
>     ENDDO
>     !write netCDF file
>     CALL writegrid(outfile,xpos,ypos,zpos,mydata,mydata2,NX,NY,NZ)
> END PROGRAM ex
>
> !Check (ever so slightly modified from www.unidata.ucar.edu)
> !:======================================================================
> SUBROUTINE check(istatus)
>     USE netcdf
>     IMPLICIT NONE
>     INTEGER, INTENT (IN) :: istatus
>     IF (istatus /= nf90_noerr) THEN
>         write(*,*) TRIM(ADJUSTL(nf90_strerror(istatus)))
>     END IF
> END SUBROUTINE check
> !:======================================================================
>
>
> !WRITEGRID - write a netCDF gridfile
>
!:=========================================================================
> SUBROUTINE writegrid(outfile,xpos,ypos,zpos,idata,idata2,NX,NY,NZ)
>     USE netcdf
>     IMPLICIT NONE
>     REAL(KIND=4), DIMENSION(NX), INTENT(IN) :: xpos
>     REAL(KIND=4), DIMENSION(NY), INTENT(IN) :: ypos
>     REAL(KIND=4), DIMENSION(NZ), INTENT(IN) :: zpos
>     REAL(KIND=4), DIMENSION(NX,NY,NZ), INTENT(IN) :: idata
>      REAL(KIND=4), DIMENSION(NX,NY,NZ), INTENT(IN) :: idata2
>     INTEGER(KIND=4) :: ncid, x_dimid, y_dimid, z_dimid
>     INTEGER(KIND=4) :: x_varid, y_varid, z_varid, varid, varid2
>     INTEGER(KIND=4), DIMENSION(3) :: dimids
>     INTEGER(KIND=4), INTENT(IN) :: NX, NY,NZ
>     CHARACTER(LEN=50), INTENT(IN) :: outfile
>     !Create the netCDF file.
>     CALL check(nf90_create(outfile, NF90_CLOBBER, ncid))
>     !Define the dimensions.
>     CALL check(nf90_def_dim(ncid, "lon", NX, x_dimid))
>     CALL check(nf90_def_dim(ncid, "lat", NY, y_dimid))
>     CALL check(nf90_def_dim(ncid, "dep", NZ, z_dimid))
>     !Define coordinate variables
>     CALL check(nf90_def_var(ncid, "lon", NF90_REAL, x_dimid, x_varid))
>     CALL check(nf90_def_var(ncid, "lat", NF90_REAL, y_dimid, y_varid))
>     CALL check(nf90_def_var(ncid, "dep", NF90_REAL, z_dimid, z_varid))
>     dimids = (/ x_dimid, y_dimid, z_dimid /)
>     !Define variable
>     CALL check(nf90_def_var(ncid, "Perturbations", NF90_FLOAT, dimids,
varid))
>     CALL check(nf90_def_var(ncid, "Pb2", NF90_FLOAT, dimids, varid2))
>     CALL check(nf90_enddef(ncid)) !End Definitions
>     !Write Data
>     CALL check(nf90_put_var(ncid, x_varid, xpos))
>     CALL check(nf90_put_var(ncid, y_varid, ypos))
>     CALL check(nf90_put_var(ncid, z_varid, zpos))
>     CALL check(nf90_put_var(ncid, varid, idata))
>     CALL check(nf90_put_var(ncid, varid2, idata2))
>     CALL check(nf90_close(ncid))
> END SUBROUTINE writegrid
>
!:=========================================================================

**Comment by coiby** [comment]
Thank you for your reply.

You are right. It's not a bug. 

I didn't take the memory order difference very serious and didn't find this doc (3.3.4 A Fortran Example of Array-Section Access)[https://www.unidata.ucar.edu/software/netcdf/netcdf/A-Fortran-Example-of-Array-Section-Access.html] before.

I didn't notice `ncdump -h` give C-style (row-major) result and I thought it's cheap to do matrix transpose (if so, netCDF should have consistent `nf90_get_var` API with the `nf90_inquire_dimension`). 

I'll close this issue. Thank you!
