### ISSUE TITLE
Anomalous (?) -lMPI::MPI_Fortran in nf-config output

### ISSUE THREAD

**Issue by maddenp** [Unidata/netcdf-fortran#321]
I'm trying to build netCDF C v4.7.4 + netCDF Fortran v4.5.4 and am seeing in the netCDF Fortran `cmake` output

```
Extra libraries:                -lnetcdf -lMPI::MPI_Fortran
```

`-lMPI::MPI_Fortran` looks suspicious to me, and appears to introduce a build error in downstream builds because it appears again in the `nf-config` output. I'd like to understand how this string would appear here, and how to prevent it, assuming I'm right in thinking that it shouldn't.

I'm attaching `reproducer.zip` containing files needed to reproduce the issue.

As background, I'm building these packages as precursors to https://github.com/NOAA-EMC/NCEPLIBS, and as an alternative to building netCDF via https://github.com/NOAA-EMC/NCEPLIBS-external, since I require `pnetcdf` support. I use `conda-build` for build/package/deploy. I suspect that `conda` has nothing to do with the issue, but am including a reproducer here that uses it, to replicate my environment closely. I think you might only need to change one or more of the three `module`-related lines at the top of `build.sh`: This is how I access the Intel compilers on my system, but yours is surely different. I have reproduced this on two separate HPC systems, administered by different vendors, with the same results.

After editing the module commands in `build.sh`, and running `./go` you should eventually find

```
$ grep "Extra libraries:.*MPI_Fortran" out
Extra libraries:                -lnetcdf -lMPI::MPI_Fortran
```

and

```
$ ./miniconda/conda-bld/bug-report_*/work/netcdff/build/nf-config | grep MPI_Fortran
  --flibs     -> -L/home/spire/pmadden/reproducer/miniconda/conda-bld/bug-report_1642266535753/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -lnetcdff -lnetcdf -lMPI::MPI_Fortran
```

This seems to have something to do with the use of `pnetcdf` because if I set `-DENABLE_PNETCDF:BOOL=OFF` in the netCDF C section of `build.sh`, `-lMPI::MPI_Fortran` does not appear in the `cmake` or `nf-config` output. I'm guessing that it comes from these lines in `fortran/CMakeLists.txt`:

```
   174  if (HAVE_NC_USE_PARALLEL_ENABLED)
   175    target_link_libraries(netcdff PUBLIC MPI::MPI_Fortran)
   176  endif()
```

I am building on `CentOS Linux release 7.5.1804 (Core)` (likely irrelevant) and using `cmake version 3.21.3`.

I'm not sure if updating to newer netCDF versions is feasible given the downstream packages I'm trying to build, so it would be great if I could identify and correct the source of the problem with these versions, whether by specifying an extra environment variable or CMake option, patching a `CMakeLists.txt` file during the build, etc.

Thanks in advance for any advice you can provide!

[reproducer.zip](https://github.com/Unidata/netcdf-fortran/files/7885307/reproducer.zip)

**Comment by maddenp** [comment]
I tried using netCDF C v4.8.1 and encountered the same thing.

**Comment by WardF** [comment]
Thanks, I'm taking a look now.  If you use `configure` to build the library instead of `cmake`, do you observe the same result in `nf-config`?

**Comment by maddenp** [comment]
Hi @WardF -- Thank you for looking into this. I'll test `configure` as soon as I can, though I doubt that `MPI::MPI_Fortran` would appear there since it seems to be an identifier leaking from CMake. We'll see!

**Comment by WardF** [comment]
@maddenp Thanks! And feel free to disregard, I've gotten an MPI environment stood up and have answered my own question.  I'm probing the boundaries of this issue and a couple others that have been revealed, but the short answer is that this is a bug that exists in cmake-based installs. It will be fixed in the next release, but in the meantime all that can be done is to either install via `configure` instead of cmake, or edit the cmake-installed `nf-config` script by hand, after installation, in order to remove the leak.

**Comment by maddenp** [comment]
Thanks @WardF. Can you tell whether `-lMPI::MPI_Fortran` should actually be `-l<some-other-lib>`, or whether it should be safe to simply remove it? I may answer my own question later if I run into `undefined symbol`, but wondered if you had a feeling about it. I'll start with the easy hack to `nf-config` and switch to the autotools build if I run into trouble with that. Thanks for validating and accepting the bug report.

**Comment by WardF** [comment]
I believe you can remove it; the mpi-specific linkage should be handled when setting the CMAKE_Fortran_COMPILER to the appropriate MPI Fortran compiler. Please let us know if you discover differently :)
