### ISSUE TITLE
/usr/bin/ld: /usr/local/lib/libnetcdf.a(attr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by waldyd** [Unidata/netcdf-fortran#35]
Hello,

While building netcdf-fortran-4.4.2 the following was prompted:

Making check in fortran
make[1]: Entering directory '/tmp/netcdf-fortran-4.4.2/fortran'
make  check-am
make[2]: Entering directory '/tmp/netcdf-fortran-4.4.2/fortran'
/bin/sh ../libtool  --tag=FC   --mode=link pgfortran  -fpic  -version-number 6:0:1  -o libnetcdff.la -rpath /usr/local/netcdf/fortran/lib typeSizes.lo module_netcdf_nc_data.lo module_netcdf_nc_interfaces.lo module_netcdf_nf_data.lo module_netcdf_nf_interfaces.lo module_netcdf_f03.lo nf_attio.lo nf_control.lo nf_dim.lo nf_misc.lo nf_genatt.lo nf_geninq.lo nf_genvar.lo nf_vario.lo nf_var1io.lo nf_varaio.lo nf_varmio.lo nf_varsio.lo    netcdf.lo netcdf3_file.lo nf_v2compat.lo module_netcdf_fortv2_c_interfaces.lo nf_fortv2.lo  -lnetcdf 
libtool: link: pgfortran -shared  -fpic -Mnomain  .libs/typeSizes.o .libs/module_netcdf_nc_data.o .libs/module_netcdf_nc_interfaces.o .libs/module_netcdf_nf_data.o .libs/module_netcdf_nf_interfaces.o .libs/module_netcdf_f03.o .libs/nf_attio.o .libs/nf_control.o .libs/nf_dim.o .libs/nf_misc.o .libs/nf_genatt.o .libs/nf_geninq.o .libs/nf_genvar.o .libs/nf_vario.o .libs/nf_var1io.o .libs/nf_varaio.o .libs/nf_varmio.o .libs/nf_varsio.o .libs/netcdf.o .libs/netcdf3_file.o .libs/nf_v2compat.o .libs/module_netcdf_fortv2_c_interfaces.o .libs/nf_fortv2.o   /usr/local/lib/libnetcdf.a    -Wl,-soname -Wl,libnetcdff.so.6 -o .libs/libnetcdff.so.6.0.1
/usr/bin/ld: /usr/local/lib/libnetcdf.a(attr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libnetcdf.a: error adding symbols: Bad value
Makefile:577: recipe for target 'libnetcdff.la' failed
make[2]: *** [libnetcdff.la] Error 2
make[2]: Leaving directory '/tmp/netcdf-fortran-4.4.2/fortran'
Makefile:741: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/tmp/netcdf-fortran-4.4.2/fortran'
Makefile:544: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

Would you please give me any idea about how to solve this issue?

Best Regards,

Néstor Waldyd

**Comment by WardF** [comment]
I suspect you need to configure netcdf-fortran with `--disable-shared`.  If this doesn't fix the issue, please send a bug report and a copy of your netcdf-fortran `config.log` to support-netcdf@unidata.ucar.edu.  Thanks!
