### ISSUE TITLE
where is the configure script?

### ISSUE THREAD

**Issue by ezaron** [Unidata/netcdf-fortran#37]

**Comment by ezaron** [comment]
I'm not sure how to install without a configure script. I tried running autoconf to generate the configure script but received many errors.

autoconf --version reports 2.69 on ubuntu 14.04

**Comment by zerothi** [comment]
Download the version tarballs, they have a configure script. cloning does
not.

2015-12-02 8:13 GMT+01:00 ezaron <notifications@github.com>:

> I'm not sure how to install without a configure script. I tried running
> autoconf to generate the configure script but received many errors.
>
> autoconf --version reports 2.69 on ubuntu 14.04
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/netcdf-fortran/issues/37#issuecomment-161204379>
> .
>



-- 
Kind regards Nick

**Comment by ezaron** [comment]
aha! thanks.

On 12/01/2015 11:36 PM, Nick R. Papior wrote:
> Download the version tarballs, they have a configure script. cloning does
> not.
>
> 2015-12-02 8:13 GMT+01:00 ezaron <notifications@github.com>:
>
> > I'm not sure how to install without a configure script. I tried running
> > autoconf to generate the configure script but received many errors.
> >
> > autoconf --version reports 2.69 on ubuntu 14.04
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/Unidata/netcdf-fortran/issues/37#issuecomment-161204379>
> > .
> >
>
>
>
> -- 
> Kind regards Nick
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Unidata/netcdf-fortran/issues/37#issuecomment-161209425>.
>

-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Edward D. Zaron
Research Assistant Professor
Department of Civil and Environmental Engineering
Portland State University
Portland, OR 97207-0751
Phone: (503)-725-2435
FAX: (503)-725-5950
zaron@cecs.pdx.edu
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by zerothi** [comment]
@ezaron please mark the issue as fixed. :)
