### ISSUE TITLE
build netcdf-fortran with CMAKE under linux red-hat

### ISSUE THREAD

**Issue by jbensabat** [Unidata/netcdf-fortran#378]
Hello 
I would like to build netcdf-fortran using cmake.
However I have not found any guidance on how to do it (as there is for building netcdf-c)
would be grateful if you could point at some ref.
best
jac

**Comment by WardF** [comment]
Hello,

The documentation for cmake needs to be fleshed out.  Do you have netcdf-c installed on your system, and is it in a standard location? I'm happy to help you with this, while I get the documentation in place.

**Comment by jbensabat** [comment]
Hi
Thank you very much. Yes it would be great if you could help me.
1. I have installed netcdf-c in the following directory /home/jb/netcdf-c/netcdf-c.4.9.0
2. I am using the intel oneapi compilers installed in /home/opt/intel/oneapi
3. the netcdf-c include files are located /home/jb/netcdf-c/netcdf-c.4.9.0/include

thanks a lot 
best
jac

**Comment by WardF** [comment]
The command-line invocation of `cmake` you will likely want to use will look like this, assuming you are starting in the `netcdf-fortran/` root directory.

    $ mkdir build
    $ cd build
    $ cmake .. -DCMAKE_Fortran_COMPILER=[fortran compiler name] -DCMAKE_PREFIX_PATH=/home/jb/netcdf-c/netcdf-c-4.9.0

You'll need to replace `[fortran compiler name]` with the appropriate name of the `oneapi` Fortran compiler.

Let me know if there's an issue/problem when you invoke these.  Thanks!

**Comment by jbensabat** [comment]
Hi 
I made progress 
Now I have the following problem. It requires the netcdf-c lib version 4.7 or higher. 
I have built the version 4.9.0, but it appears that the script is looking for the netcdf lib in the directory /usr/lib64 
where there is already a netcdf lib that is old. Since others are using this computer, how can change the script to it looks for the libs I have built in the directories that I can specify ?
thanks
jac

**Comment by WardF** [comment]
When invoking cmake, the `CMAKE_PREFIX_PATH` variable should take precedence.  So pointing that to the location of your install for v4.9.0 should work.  After building the `netcdf-c` library, are you running `make install`, or are you trying to use it from the build directory?

**Comment by jbensabat** [comment]
Hi 
I did not run make install - I just left the libs in the build directory
should  run make install ?
if yes ? from the build directory ?
best
jac

**Comment by mcgeochd** [comment]
Sorry to piggyback on this, I can open another issue if necessary. I'm trying to build netcdf-fortran on windows 10 using my WSL2 Ubuntu instance, I've cloned the repository using GitHub Desktop and have the run the following from the build directory I created:
```
mcgeochd@DESKTOP-LIAD1LH-wsl:/mnt/c/Users/domin/OneDrive/Documents/GitHub/netcdf-fortran/build$ cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_PREFIX_PATH=/mnt/c/Program Files/netCDF-c-4.9.0
CMake Error: The source directory "/mnt/c/Users/domin/OneDrive/Documents/GitHub/netcdf-fortran/build/Files/netCDF-c-4.9.0" does not exist.
```
I installed netcdf-c-4.9.0 for windows from the prebuilds here https://docs.unidata.ucar.edu/netcdf-c/current/winbin.html, though I had to rename the folder to remove the spaces in the name. When I installed it it failed to add itself to my windows path automatically with a warning that the PATH variable value was too long, though I'm not sure if that's the issue.

I also have automake/autotools and make installed on my WSL2 Ubuntu instance if those can alternatively be used?

**Comment by jbensabat** [comment]
Hello 
I tried to run make install from the build directory in netcdf-c 
it failed because it did not have access to the the /usr/lib64 directory (dont have provileges and also there is a previous version of netcdf-c installed there)
then I tried make instead of make install and then I have no error and the library is built and stored locally in the liblib directory 
however, when I tried to build the fortran lib using the commands you supplied it still looks for the libs in /usr/lib64 directory and I get an error that the version is not correct. Actually it finds an older lib
any way around this ?
best
jac

**Comment by jbensabat** [comment]
Good morning 
I am really stuck with this 
any help would really be appreciated 
thanks
jac

**Comment by WardF** [comment]
Hi.  When you run `cmake`, you can specify an install location by passing `-DCMAKE_INSTALL_PREFIX=[location you have write access to]`.  This is where the library will be installed when you run `make install`.

**Comment by jbensabat** [comment]
hi 
thanks a lot 
I have it clear now. My error was that I did not point in -DCMAKE_INSTALL_PREFIX to the directory where the lib is available.
thanks 
jac
