### ISSUE TITLE
nf-config --libdir points to wrong directory

### ISSUE THREAD

**Issue by magnusuMET** [Unidata/netcdf-fortran#380]
* netcdf-fortran 4.6.0
* Rhel8 amd64

When building netcdf-fortran with cmake the installation directory of the library will be at $LIBDIR/lib64, although the [nf-config](https://github.com/Unidata/netcdf-fortran/blob/964843374548330c32caa6cccb81a6765c783bbc/nf-config.cmake.in#L9) configuration assumes the installation directoy is $LIBDIR/lib (withouth the necessary `64` at the end). I believe `https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs` can be used to set the correct directory.

**Comment by WardF** [comment]
Thanks!

**Comment by kasra-keshavarz** [comment]
I have the same issue but `nf-config` is pointing to `lib` rather than `lib64`. Not sure how I can tackle this. Let me know if you need more information from my side.

**Comment by WardF** [comment]
I know this is quite an old issue, but what version of `netcdf-fortran` is being used? `nf-config` does not appear to have a `--libdir` argument, which seems like an oversight. Does `nf-config --flibs` demonstrate the same issue?

**Comment by WardF** [comment]
Thanks! I think I have a fix, I'm testing now.

**Comment by WardF** [comment]
This should hopefully be corrected now. We're working on getting netCDF-C `v4.9.3` out ASAP, after which we'll try to get netcdf-fortran v4.6.2 out right afterwards.
