### ISSUE TITLE
Difficulty reading array dimensions

### ISSUE THREAD

**Issue by rouson** [Unidata/netcdf-fortran#381]
I'm using netcdf-fortran commit 964843374548330c32caa6cccb81a6765c783bbc on macOS 12.6 and attempting to modify `examples/F90/simple_xy_rd.F90` to read the `data_in` array dimensions and use them to allocate `data_in` rather than hardwiring the dimensions (`NX` and `NY`) in a `parameter` declaration

I added the declaration
```
  integer, dimension(2) :: dimids, dims
```
and then I added the following two lines after the line `call check( nf90_get_var(ncid, varid, data_in) )`:
```
  call check(nf90_inquire_variable(ncid, varid, dimids=dimids))
  call check(nf90_get_var(ncid, varid=dimids(1), values=dims(1)))
```
Executing the resulting program gave
```
 NetCDF: Variable not found
STOP 2
<ERROR> Execution failed for object " simple_xy_rd "
<ERROR>*cmd_run*:stopping due to failed executions
STOP 1
```
I was imagining that the call to `nf90_inquire_variable` would load the netCDF IDs for the the dimensions of the `data_in` array into the `dimids` array.  I thought that `nf90_get_var` call would then load the `data_in` dimensions into the `dims` array.

Please let me know where I was mistaken and how to read the dimensions of `data_in` so that I can use them to allocate `data_in` rather than hardwiring the dimensions to be allocated in the manner of netcdf-fortran's `simple_xy_rd.F90` example.

**Comment by WardF** [comment]
So to get the lengths of the dimensions you'll need to use a call to `nf90_inquire_dimension`.  I removed the following line:

````
 call check(nf90_get_var(ncid, varid=dimids(1), values=dims(1)))
````

and replaced it with the following:

````
  do x = 1, 2
    call check( nf90_inquire_dimension(ncid, dimids(x), len=dims(x)))
    print *, "dimids(", x,") length = ", dims(x)
  end do

````

Running this provides the following output:

````
dimids(           1 ) length =           12
dimids(           2 ) length =            6
````

At this point, `dims()` should contain the information you need to allocate dynamically.  I hope this helps!
