### ISSUE TITLE
Wrong tar file

### ISSUE THREAD

**Issue by ecanesc** [Unidata/netcdf-fortran#385]
The tar file

https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.tar.gz

is not netcdf-fortran, it is netcdf-c:

% tar tvf v4.6.0.tar.gz | more
drwxrwxr-x root/root         0 2018-01-24 20:08 netcdf-c-4.6.0/
...

The zip file v4.6.0.zip is correct.

**Comment by WardF** [comment]
Clicking the link you provided downloads the Fortran tarball for me, so I am a bit at a loss.  Particularly as the tar.gz file is automatically generated by GitHub when the release is minted, and not something we manually uploaded.

**Comment by ecanesc** [comment]
Hmm, I downloaded it twice to be sure, but now I get the right one too. I think it would be helpful if the tar file was named netcdf-fortran-4.6.0.tar.gz, not v4.6.0.tar.gz, to avoid getting it confused with netcdf-c, which also uses the same abbreviated naming scheme.

**Comment by WardF** [comment]
When I download the file from the release page here, https://github.com/Unidata/netcdf-fortran/releases/tag/v4.6.0, I get a file with the name `netcdf-fortran-4.6.0.tar.gz` or `netcdf-fortran-4.6.0.zip`.  Likewise, when I click the link embedded in the top post of this issue, I get a file named 'netcdf-fortran-4.6.0.tar.gz`.  I am at a loss as to how anybody is getting a file named `v4.6.0.tar.gz`. I know if you hover over the link that it is represented as such as part of the GitHub back-end scheme, but that's not the file name that is delivered when you click it.   

If the file is being downloaded via an automated process using `curl` or `wget`, there are command line options to let you name the resultant file whatever you like.  However, I'm still at a loss and would like to understand how we're getting the observed result in the first place.  @ecanesc and @Dave-Allured, how are you downloading the files, and can you confirm that you *don't* get the `netcdf-fortran` prefix on the file you download?

**Comment by WardF** [comment]
I'm able to recreate this if I use `wget`; it does not follow the redirects and does in fact download `v4.6.0.tar.gz`.  This is a pretty easy fix, however; in whatever script is calling `wget`, you can add the `-O netcdf-fortran-4.6.0.tar.gz` argument.  This could be parameterized and generated at run-time pretty easily, I would think :).

**Comment by Dave-Allured** [comment]
@WardF, thank you for your prompt attention.  I just confirmed the OP's reported problem, at least the "wrong filename" part.

1.  Go to the main Github page for Unidata/netcdf-fortran.
https://github.com/Unidata/netcdf-fortran

2.  FWIW, the selected branch showing in the upper left is "main".  Probably does not matter.

3.  In the right hand sidebar, scroll down to Releases, and click on "netCDF-Fortran v4.6.0".  That lands me here:
https://github.com/Unidata/netcdf-fortran/releases/tag/v4.6.0

4.  Scroll to "Assets" down at the bottom.  There are the two offending links.

Source code (zip)                          Jul 29
https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.zip

Source code (tar.gz)                     Jul 29
https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.tar.gz

I checked the tar.gz version.  The top level directory on the inside is netcdf-fortran-4.6.0.  The internal time stamp on this directory is 2022 July 29.  That seems about right.

**Comment by WardF** [comment]
Thanks for double checking @Dave-Allured! If yo click those links, do you get a file `v4.6.0.zip` or `v4.6.0.tar.gz`, or do you get a file with the `netcdf-fortran` prefix?

**Comment by WardF** [comment]
As you can see from the attached screenshot, I am getting a properly named file.  I've only tested with Chrome and Safari, so if you are getting something different, I'd be very interested to know which browser/circumstances.  Thanks for helping figure this out :)

* ![Screenshot 2022-12-07 at 4 16 27 PM](https://user-images.githubusercontent.com/4324946/206317786-436681b6-b844-4f4f-8993-1b73667c2470.png)

**Comment by Dave-Allured** [comment]
I don't know how @ecanesc does it.  Personally I hover, then right click, then Copy Link.  Then I leave the browser and go to a terminal window.  Then, e.g.:

curl -O -R -L https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.tar.gz

**Comment by Dave-Allured** [comment]
About that "-L" in my curl command.  It is essential when downloading with curl.
* Leave it out, and you get a zero length file.
* With "-L", there is a redirect visible in the progress display, and I get the intended file.

**Comment by WardF** [comment]
@Dave-Allured Thanks! It looks like if you add `-J` to your invocation, you should get the expected filename: 

    $ curl -O -R -J -L https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.tar.gz

Let me know if that doesn't work on your end, but adding `-J` gives me `netcdf-fortran-4.6.0.tar.gz`, as expected.  From `man curl`,

````
  -J, --remote-header-name
              (HTTP) This option tells the --remote-name option to use the server-specified Content-Disposition filename
              instead of extracting a filename from the URL. If the server-provided file name contains a path, that will be
              stripped off before the file name is used.

(...)
````

Hopefully, this command-line switch is ubiquitous across modern curl implementations, and will work in your environment.

**Comment by WardF** [comment]
Similarly, it looks like with `wget` you can pass `--content-disposition` to achieve the same result, e.g. 

    $ wget --content-disposition https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.6.0.tar.gz

Given that it appears we can fix this by argument passing, instead of breaking with the established tag naming convention (from which the file name is derived), and since browser-based downloads have been working, I'm hoping we can call this issue closed.  I'll wait to hear if further issues present themselves, however; the issue has been open this long, a little while longer won't hurt.

**Comment by Dave-Allured** [comment]
--- OPINION ---

Requiring users to become aware of content-disposition and add an extra command option, is not conventional or user friendly.  Best would be if you could figure out how to sidestep this "tag naming convention" and control your own artifact file names on the github site.  I don't know how difficult that might be.

But at least, thanks for figuring out what is going on.

**Comment by WardF** [comment]
No problem, thanks again for your help figuring this out!
