### ISSUE TITLE
gcc: error: unrecognized command-line option '-V'

### ISSUE THREAD

**Issue by htan2013** [Unidata/netcdf-fortran#391]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue: netcdf-fortran-4.5.3
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.) Ubuntu 20, gcc11.3.0
* a description of the issue with the steps needed to reproduce it: 
 ./configure --prefix=/home/htan/netcdf --disable-dap --disable-netcdf-4 --disable-shared FC=gfortran

Dear all,
I tried to compile netcdf-c and netcdf-f. The netcdf-c was compiled successfully. However, the fortran one met this issue with gcc:

Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-pre>Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
... rest of stderr output deleted ...
configure:3921: $? = 0
configure:3910: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3921: $? = 1
configure:3910: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.

Appreciate many thanks in advance.
Haochen

**Comment by cmdelta** [comment]
I have the same problem, I am using gcc located /usr/bin/gcc, the version is 11.3.0.
The netcdf-c was compiling well, but got the same error when compiling netcdf-fortran.
Thank you very much!
Alex

> gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
... rest of stderr output deleted ...
configure:3939: $? = 0
configure:3928: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3939: $? = 1
configure:3928: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:3939: $? = 1
configure:3959: checking whether the C compiler works
configure:3981: gcc -I/home/alex/Build_WRF/LIBRARIES/grib2/include -L/home/alex/Build_WRF/LIBRARIES/grib2/lib conftest.c -lnetcdf -lz >&5
/usr/bin/ld: cannot find -lnetcdf: No such file or directory
collect2: error: ld returned 1 exit status
configure:3985: $? = 1
configure:4023: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "netCDF-Fortran"
| #define PACKAGE_TARNAME "netcdf-fortran"
| #define PACKAGE_VERSION "4.5.2"
| #define PACKAGE_STRING "netCDF-Fortran 4.5.2"
| #define PACKAGE_BUGREPORT "[support-netcdf@unidata.ucar.edu](mailto:support-netcdf@unidata.ucar.edu)"
| #define PACKAGE_URL ""
| #define PACKAGE "netcdf-fortran"
| #define VERSION "4.5.2"
| /* end confdefs.h. */
|
| int
| main ()
| {
|
| ;
| return 0;
| }
configure:4028: error: in `/home/alex/Build_WRF/LIBRARIES/netcdf-fortran-4.5.2':
configure:4030: error: C compiler cannot create executables
See `config.log' for more details

**Comment by WardF** [comment]
The failure to parse `-V` isn't an error in and of itself.  The `configure` script is meant to determine various things about your environment which are then used to create the resultant `Makefile`'s.  Part of this is trying a **lot** of different things, seeing what works, and seeing what fails.  So that's not unsurprising.

Can you attach your config.log file?  When `configure` returns a non-zero failure, the *last* error reported in the file is usually the pertinent one.

**Comment by WardF** [comment]
NetCDF-Fortran does not have the `--disable-dap` and `--disable-netcdf-4` options; you can omit these.  They are a holdover from when the library provided Fortran, C and C++ API's as an all-in-one bundle; starting with netCDF `4.2`, however, we separated into different libraries.
