### ISSUE TITLE
CDF-5 failed checks

### ISSUE THREAD

**Issue by douglowe** [Unidata/netcdf-fortran#401]
I've compiled netcdf-fortran 4.6.1, with netcdf-c 4.9.2, and HDF5 1.14.1. The build checks fail for CDF-5, and a couple of other checks (which I've not quite managed to identify from the logs). Attached are the log files for the build.

[config-4.9.2.log](https://github.com/Unidata/netcdf-fortran/files/11579808/config-4.9.2.log)
[make-4.9.2.log](https://github.com/Unidata/netcdf-fortran/files/11579809/make-4.9.2.log)
[make-check-4.9.2.log](https://github.com/Unidata/netcdf-fortran/files/11579811/make-check-4.9.2.log)
[test-suite.log](https://github.com/Unidata/netcdf-fortran/files/11579832/test-suite.log)

**Comment by WardF** [comment]
I'm a bit at a loss as to what's going on, as I'm unable to recreate this issue on my end using the same library versions (4.6.1, 4.9.2, 1.14.1).  Which version of which Linux distro are you working with? It's a long shot, but it's the next thing I can think of to try to recreate this.

**Comment by douglowe** [comment]
It's CentOS Linux release 7.9.2009 (Core) - on a HPC system, so unfortunately not due to be updated anytime soon.

**Comment by douglowe** [comment]
Could you advise me which code exactly is failing - then I can try here to compile some smaller tests to focus specifically on these, that our infrastructure team can test out too.

**Comment by douglowe** [comment]
Scratch this question, I've found my error - I had managed to mangle my LD_LIBRARY_PATH. Fixing that has sorted all the CDF-5 problems (I've still had to disable the zstandard plugin, but I'm not fussed about that).

**Comment by WardF** [comment]
Thank you for the update; this will at least arm us with more information should others encounter the same issue!
