### ISSUE TITLE
Cmake modernization

### ISSUE THREAD

**Issue by LecrisUT** [Unidata/netcdf-fortran#404]
This should be moved into the main netcdf-c project, ensuring the library versions are equivalent

**Comment by WardF** [comment]
These were split off after netcdf 4.1.3, and it is unlikely they will be recombined.

**Comment by LecrisUT** [comment]
Then please re-open as a mirror issue to https://github.com/Unidata/netcdf-c/issues/2713. And in addition to those points:
- make netcdf-c a submodule dependency
- add an organization wide github workflow
- synchronize or delegate one library to have the main cmake files (defining macros and so on)

---

I believe there are more disadvantages in keeping these organized as individual repositories and much more CI complexity to be designed and maintained than there is advantages. Is there a discussion for the split off decision to be read and can it be reconsidered in light of the advances of the build system tools?

**Comment by LecrisUT** [comment]
@WardF, please re-open this issue because this is still relevant with the comments linked to the C library. Why is the fortran interface namespaced as `netCDF::netcdft`? It should be `netCDF::Fortran` or equivalent.
https://github.com/Unidata/netcdf-fortran/blob/5f02e6a08432062cfcf98c85bf0d71e71408820c/fortran/CMakeLists.txt#L210-L211
