### ISSUE TITLE
Issues with the configuration with default HDF5 path

### ISSUE THREAD

**Issue by coderodyhpc** [Unidata/netcdf-fortran#411]
Sorry but I don't understand the solution to #403 . I have tried installing hdf5plugin hoping that it might create a specific directory and define HDF5_PLUGIN_PATH but it hasn't fixed the issue. I have 2 questions: (1) How would you use nc-config to overcome this error as suggested by @**WardF**; (2) I don't know much about zstd other than it is lossless and yields a good compression ratio, but is it really beneficial while working with netCDF? Thanks.
P.S. I'm installing netCDF-fortran from the master branch and netCDF v4.9.2.

**Comment by edwardhartnett** [comment]
Did you resolve this? WHat was the answer?

**Comment by amd-krishnoz** [comment]
How did you install `hdf5plugin` and from where ?
