### ISSUE TITLE
undefined filter encountered

### ISSUE THREAD

**Issue by dkokron** [Unidata/netcdf-fortran#412]
Using netCDF fortran (4.6.0) built on top of NetCDF-4.9.2 and HDF5-1.14.0 in a SLES15 sp3 environment.  It's a Cray system, but  everything is built with Intel compilers (19.1.3.304).

We are encountering the following runtime error while reading one of our restart files (grid_spec.nc)

NetCDF: Filter error: undefined filter encountered: get_variable_num_dimension: file:INPUT/grid_spec.nc variable: gridfiles

ncdump -h of grid_spec.nc

netcdf grid_spec {
dimensions:
	ntiles = 1 ;
	string = 255 ;
variables:
	char mosaic(string) ;
		mosaic:standard_name = "grid_mosaic_spec" ;
		mosaic:children = "gridtiles" ;
		mosaic:contact_regions = "contacts" ;
		mosaic:grid_descriptor = "" ;
	char gridlocation(string) ;
		gridlocation:standard_name = "grid_file_location" ;
	char gridfiles(ntiles, string) ;
	char gridtiles(ntiles, string) ;

// global attributes:
		:grid_version = "0.2" ;
		:code_version = "$Name: fre-nctools-bronx-10 $" ;
		:history = "/scratch1/BMC/gsd-fv3-dev/USER/frac_soil_veg/driver_scripts/../exec/make_solo_mosaic --num_tiles 1 --dir /scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp3/USER/fv3_grid.regional_esg/regional/grid --mosaic C3463_mosaic --tile_file C3463_grid.tile7.nc" ;
		:_Format = "64-bit offset" ;
}

I tried building a small reproducer (attached) to check the filter attributes (nf90_inq_var_filter) but ran into a "insufficient virtual memory" error at runtime.  I notice there aren't any builtin tests for this routine.

[NetCDF_check_gridfiles.f90.gz](https://github.com/Unidata/netcdf-fortran/files/12612774/NetCDF_check_gridfiles.f90.gz)

Wondering if there are still issues with these filter routines when a variable does not have filter attributes set?

https://docs.unidata.ucar.edu/netcdf-c/current/filters.html
"The function *_nc_inq_var_filter* was returning the error value NC_ENOFILTER if a variable had no associated filters. It has been reverted to the previous case where it returns NC_NOERR and the returned filter id was set to zero if the variable had no filters."

**Comment by DennisHeimbigner** [comment]
Try doing the command "ncdump -hs grid_spec.nc"
That should report what filters are used by the file.

**Comment by dkokron** [comment]
ncdump -hs /lfs/h2/hpc/support/daniel.kokron/Projects/RRFS/fcst_fv3lam_spinup/INPUT.20230725.190000.ReStripe/grid_spec.nc
netcdf grid_spec {
dimensions:
	ntiles = 1 ;
	string = 255 ;
variables:
	char mosaic(string) ;
		mosaic:standard_name = "grid_mosaic_spec" ;
		mosaic:children = "gridtiles" ;
		mosaic:contact_regions = "contacts" ;
		mosaic:grid_descriptor = "" ;
	char gridlocation(string) ;
		gridlocation:standard_name = "grid_file_location" ;
	char gridfiles(ntiles, string) ;
	char gridtiles(ntiles, string) ;

// global attributes:
		:grid_version = "0.2" ;
		:code_version = "$Name: fre-nctools-bronx-10 $" ;
		:history = "/scratch1/BMC/gsd-fv3-dev/Ning.Wang/frac_soil_veg/driver_scripts/../exec/make_solo_mosaic --num_tiles 1 --dir /scratch1/BMC/gsd-fv3-dev/NCEPDEV/stmp3/Ning.Wang/fv3_grid.regional_esg/regional/grid --mosaic C3463_mosaic --tile_file C3463_grid.tile7.nc" ;
		:_Format = "64-bit offset" ;
}

**Comment by DennisHeimbigner** [comment]
Are you using the netcdf-c ncdump or the netcdf-java ncdump?

**Comment by dkokron** [comment]
4.9.2/bin/ncdump

**Comment by DennisHeimbigner** [comment]
Wait, how was that file created? Did you use the netcdf-c library or something else?

**Comment by dkokron** [comment]
It was made by someone else using a tool I am not familiar with.  The file works fine using our standard hdf5-1.10.6+netcdf-4.7.4 setup.

**Comment by DennisHeimbigner** [comment]
Well try this command, although the output may be large, and post it or send it to me (dmh@ucar.edu)
````
h5dump -p INPUT.20230725.190000.ReStripe/grid_spec.nc
````

**Comment by dkokron** [comment]
h5dump --version
h5dump: Version 1.14.0

h5dump -p INPUT.20230725.190000.ReStripe/grid_spec.nc
h5dump error: unable to open file "INPUT.20230725.190000.ReStripe/grid_spec.nc"

file INPUT.20230725.190000.ReStripe/grid_spec.nc
INPUT.20230725.190000.ReStripe/grid_spec.nc: data

od -c INPUT.20230725.190000.ReStripe/grid_spec.nc | head
0000000   C   D   F 002  \0  \0  \0  \0  \0  \0  \0  \n  \0  \0  \0 002

**Comment by DennisHeimbigner** [comment]
It appears that this file is not an HDF5 file nor a netcdf-4 file.
So the question is: what kind of file is it? Any ideas?

**Comment by dkokron** [comment]
ncdump -k INPUT.20230725.190000.ReStripe/grid_spec.nc
64-bit offset

I reached out to the author of the make_solo_mosaic tool.  Hopefully they can add some insight.

**Comment by DennisHeimbigner** [comment]
The original error was a complaint about an undefined filter.
The issue seems to be this: we have no easy way to find out what filters it is using, if any.
Normally we can find that out using h5dump -p or ncdump -hs.
We need some insight into what filters are being used and how in that file.

**Comment by dkokron** [comment]
What if no filters are used?  How does the NetCDF code handle that situation?

**Comment by DennisHeimbigner** [comment]
It just returns the data from the file and makes no attempt to apply any filter.

**Comment by dkokron** [comment]
Do you see any issues with the simple code I attached at the beginning of this thread?

**Comment by DennisHeimbigner** [comment]
The code is ok, but if in effect the file being read is malformed with respect to netcdf-4,
then it should return an error.

**Comment by edwardhartnett** [comment]
The ncdump shows the file is in 64bit offset format, not netcdf4

**Comment by dkokron** [comment]
Compiling my little tester with the older environment (hdf5-1.10.6+netcdf-4.7.4) results in
./NetCDF_check_gridfiles.x
 NetCDF: Attempting netcdf-4 operation on netcdf-3 file
2

This is much more useful than what I get with hdf5-1.14.0 + netcdf-4.9.2
./NetCDF_check_gridfiles.x
forrtl: severe (41): insufficient virtual memory
Image              PC                Routine            Line        Source
libifcoremt.so.5   0000145E18978548  for_allocate          Unknown  Unknown
libnetcdff.so.7.1  0000145E19C6D7CA  nf_inq_var_filter     Unknown  Unknown
libnetcdff.so.7.1  0000145E19CC3A6E  netcdf_mp_nf90_in     Unknown  Unknown
NetCDF_check_grid  0000000000401222  MAIN__                     27  NetCDF_check_gridfiles.f90

**Comment by dkokron** [comment]
This issue turned out to result from me not rebuilding all application dependencies with the hdf5-1.14.0 + netcdf-4.9.2 combination.

**Comment by DennisHeimbigner** [comment]
Thanks Ed, I should have done an ncdump -k check.
That does raise an issue. When applied to a netcdf-3 file,
should nc_inq_var_filter return an error, or just pretend there
are no filters?

**Comment by edwardhartnett** [comment]
Well if NC_NOT_NC4 could be returned, that would be best.
