### ISSUE TITLE
Cannot find `configure` script to compile netCDF-Fortran

### ISSUE THREAD

**Issue by EZoni** [Unidata/netcdf-fortran#415]
Hi all,

I'm new to netCDF and I'm trying to install the Fortran library on my Linux Ubuntu 20.04 LTS machine.

I installed the netCDF-C library successfully and I'm following the docs here, https://docs.unidata.ucar.edu/netcdf-c/current/building_netcdf_fortran.html, to build and install the Fortran counterpart.

Point 5. of section "Building with shared libraries" has the following code snippet:
```
CPPFLAGS=-I${NCDIR}/include LDFLAGS=-L${NCDIR}/lib \
./configure --prefix=${NFDIR}
```
and says to execute this from the "top-level source directory".

However, I cannot find the `configure` script mentioned above.

These are the only files that I can find which contain the `config` string in their name:
```
$ ll *config*
-rw-rw-r-- 1 edoardo edoardo  7714 Nov  3 08:53 config.h.cmake.in
-rw-rw-r-- 1 edoardo edoardo 25867 Nov  3 08:59 configure.ac
-rw-rw-r-- 1 edoardo edoardo  2422 Nov  3 08:53 nf-config.cmake.in
-rw-rw-r-- 1 edoardo edoardo  2963 Nov  3 08:53 nf-config.in
```

Am I looking in the wrong directory or misunderstanding something?

Or am I supposed to make the `configure.ac` file executable (`chmod +x configure.ac`)
and then run that script (in which case I guess the docs would need to be updated)?

Thank you in advance for your help!

**Comment by WardF** [comment]
You will need to download one of the releases, which come bundled with the `configure` scripts and other support files.  You can find these at https://github.com/Unidata/netcdf-fortran/releases.  If you download the development branch, it will not contain the generated `configure` script.  I hope this helps!
