### ISSUE TITLE
run_f90_par_examples.sh fails on parallel systems.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-fortran#42]
As reported in #41, `run_f90_par_examples.sh` is failing to run properly.  

```
FAIL: run_f90_par_examples.sh
=============================

 *** SUCCESS writing example file simple_xy_par.nc! 
 *** SUCCESS reading example file simple_xy_par.nc! 
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_va
STOP 2
STOP 2
STOP 2
```

**Comment by climbfuji** [comment]
Hi, I am facing the same problem with netcdf-fortran-4.4.4 (hdf5-1.8.16, pnetcdf-1.6.1, netcdf-c-4.4.1) on RH Scientific Linux 7.2, Intel Compiler 15.0.4, mvapich2-2.2b (and mpich-3.1.4). Is there any solution yet? Is this just a test problem or a general problem with the library, i.e. can I ignore it and proceed? Thanks.

**Comment by WardF** [comment]
No progress yet, but I believe that you can ignore this issue, and it is just a test problem.  The good news is that if I'm wrong and it's *not* just a test problem, it should be readily visible!

**Comment by zerothi** [comment]
FYI, just to let you know, 

I have this setup:
compiler: GCC-6.1.0
mpi: OpenMPI 1.10.2
hdf5: 1.8.16
netcdf-c: 4.4.0
netcdf-fortran: 4.4.3
pnetcdf: 1.7.0

Using OpenMPI 1.8.2 and gcc-6.1.0

Here is the output from fortran test:
PASS: simple_xy_wr
PASS: simple_xy_rd
PASS: sfc_pres_temp_wr
PASS: sfc_pres_temp_rd
PASS: pres_temp_4D_wr
PASS: pres_temp_4D_rd
PASS: simple_xy_par_wr
PASS: simple_xy_par_rd
PASS: simple_xy_par_wr2
PASS: simple_xy_nc4_wr
PASS: simple_xy_nc4_rd

**Comment by zerothi** [comment]
Ok, I have just tried a few different version configurations:

I have this setup:
compiler: GCC-6.1.0
mpi: OpenMPI 1.10.2
hdf5: 1.8.16
pnetcdf: 1.7.0

Then I tried with different versions (C=netcdf-c, F=netcdf-fortran):
OK means all parallel tests are passing, FAIL means the run_f90_par_examples.sh test is failing
C=4.4.0, F=4.4.3 OK
C=4.4.0, F=4.4.4 FAIL
C=4.4.1, F=4.4.3 OK
C=4.4.1, F=4.4.4 FAIL

It seems it only appears in 4.4.4?
It was not clear whether this was already clear to you. So I did it :)

**Comment by WardF** [comment]
Thanks for making that matrix; I'm looking at it now.  Offhand, I'm wondering if it might be related to pnetcdf; there is a known issue with netCDF-C and pnetcdf 1.7.0; the previous 1.6.x version works as well.  I'm recreating this on my end and will see if it makes a difference

**Comment by zerothi** [comment]
I can try with the 1.6.<latest> tomorrow if you want?

**Comment by WardF** [comment]
I'm running through it now and will report results here; if 1.6 fixes the issue, that's at least a workaround.  If it's unrelated, I'll post that too.

**Comment by WardF** [comment]
The failures did not occur for me using pnetcdf 1.6.1, I am trying to construct an environment now with 1.7.0.  It's clear something is going on here, we just need to narrow down what, exactly.

**Comment by WardF** [comment]
I'm unable to recreate this issue right now in my environments, using Ubuntu-based docker environments (https://github.com/Unidata/docker-nctests).  Will continue to try to recreate, but no failures using either 1.6.1 or 1.7.0.

**Comment by climbfuji** [comment]
Hi Ward and Nick,

thanks for your efforts. I am not using pnetcdf-1.7.0 because of other problems that occur and that you are already aware of - unit tests related to schar variables failing.

To confirm, I just repeated the unit tests using netcdf-c-4.4.1, netcdf-cxx4-4.3.0, netcdf-fortran-4.4.3, pnetcdf-1.6.1, hdf5-1.8.16, zlib-1.2.8, szip-2.1, mvapich2-2.2b / mpich-3.1.4, intel-15.0.4 - all tests pass. I.e., the problem seems to be related to netcdf-fortran-4.4.4.

Thanks again for all your help.

Maybe it would be worthwhile collecting “combinations known to work” somewhere on unidata’s website?

Cheers

Dom

**Comment by WardF** [comment]
Hi @climbfuji I appreciate your efforts building this compatibility matrix.  There were a lot of changes made between netCDF fortran 4.4.3 and 4.4.4; it also doesn't help that our Fortran expert has retired and I'm a relative newbie with it.  

I know I've recreated this issue previously; once I'm able to recreate it again (currently, everything is working for me regardless of using Fortran 4.4.3 and 4.4.4) I'll be able to say specifically what is going on, and can put a note on the website.  Right now, I can't be certain whether it's the code itself, something in the environment/a dependency, or some combination thereof.  

You've been a great help narrowing it down so far. I'll follow up once I have made some progress duplicating this.

**Comment by danielog2073** [comment]
Hi,

My configuration is netcdf-c-4.4.1-rc2, pnetcdf-1.7.0, HDF5-1.8.17, icc 15.0.1, mpiicc, mpiifort and when I build the netcdf-fortran-4.4.4 and run the test run_f90_par_examples.sh me too obtained the same error:
[root@service1 F90]# ./run_f90_par_examples.sh 
 *** SUCCESS writing example file simple_xy_par.nc! 
 *** SUCCESS reading example file simple_xy_par.nc! 
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_v
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_v
 NetCDF: Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_v
 a
 a
 a
2
2
2
But when I build netcdf-fortran-4.4.3 with the same configuration all tests passed.Is It safe to use netcdf-fortran-4.4.4 with there error?

Thanks for you help

**Comment by marshallward** [comment]
Hi, I am having the same problem.  I'm not using pnetcdf, just HDF5 for parallel (or that's the plan, at least).

This is my build, using OpenMPI 1.10.2:

hdf5-1.8.17
```
    CC=mpicc ./configure --prefix=/short/fp0/mxw900/hdf5 --enable-parallel --enable-fortran
```

netcdf-c 4.4.1
```
CC=mpicc CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib \
    ./configure \
    --prefix=${NCDIR} \
    --disable-dap --enable-parallel-tests \
    --enable-remote-fortran-bootstrap  # Probably not working, had to build manually
```

netcdf-fortran v4.4.4
```
CC=mpicc FC=mpifort F77=mpif77 \
    CPPFLAGS=-I${NCDIR}/include LDFLAGS=-L${NCDIR}/lib \
    ./configure \
    --prefix=${NFDIR} \
    --enable-parallel-tests
```

Not sure the best info to provide here, please feel free to follow up.  I'll try 4.4.3 and see how it goes.

**Comment by WardF** [comment]
My apologies for the delayed response; I was out of the office for the Thanksgiving Holiday.  I'll try to replicate the issue as reported by @marshallward since that is not using the parallel netcdf library.  What platform are you on if I may ask, @marshallward ? I test on Ubuntu by default but can try to create a similar environment if you are using a different Linux distribution.

**Comment by marshallward** [comment]
CentOS 6.8, but much of the software is custom-built so that may not be much help.

The only other info I can add is that my HDF5 installation failed on one of its tests related to the flush() call.  (Actually the test reported success but the cleanup failed!)

I haven't done justice yet looking into this yet, I only relied on the "make check" scripts.  I'll try to get some more info on what is happening.

**Comment by marshallward** [comment]
The full error in `libdispatch/derror.c` explains it better than I could:

> NetCDF:  Attempt to extend dataset during NC_INDEPENDENT I/O operation. Use nc_var_par_access to set mode NC_COLLECTIVE before extending variable."

i.e. since there's an unlimited dimension, the `nf90_put_var` call needs `NC_COLLECTIVE` to be enabled.

I tried replacing `NC_INDEPENDENT` with `NC_COLLECTIVE` but this hangs because rank 0 is not used in the test.  I removed the rank test, and it succeeded, but I'm probably not honoring the spirit of the test anymore.  (It looks like the original intent was to test independent writes, but it seems this is no longer possible.)

I've prepared a pull request (#56) with a slightly modified version, swapping to collective writes and removing the rank 0 check.

**Comment by WardF** [comment]
Thanks for the pull request; I'll be merging it shortly, closing out this issue as I was able to finally duplicate the problem, and then observe that it is fixed by the pull request referenced here.

**Comment by marshallward** [comment]
Good to hear, thanks for the update.

It is probably still a good idea to test independent parallel writes at some point, but I don't feel close enough to the project to start introducing new tests.

**Comment by ssgmath** [comment]
Has there been any further leads/developments following up on these issues with independent parallel writes? I am currently porting my code from PnetCDF to NETCDF4 (primarily to allow unlimited dimensions) - the independent write routines/tests with rank 0 fail similarly still with NETCDF4.4.1.1.6.

**Comment by WardF** [comment]
Hello @ssgmath 

Can you try testing against the latest netCDF-Fortran `master` branch?  We are also preparing the next Fortran release for within the next week or so.  It should contain this fix.

**Comment by ssgmath** [comment]
I did give it a try with the latest NetCDF-Fortran (4.4) but the same error persists. Is it true that that independent writes just don't work with unlimited dimensions requirement?
On a related note, the relevant documentation I have been consulting has left me a bit confused: 
1. https://www.unidata.ucar.edu/software/netcdf/docs/parallel_io.html#collective_independent - seems to suggest that independent writes are the deafult and one must use var_par_access to switch to collective write mode?
2. https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-f77/NF_005fCREATE_005fPAR.html#NF_005fCREATE_005fPAR - the (fortran) create routine documentation seems to suggest collective operations are default - so in this case no call to var_par_access is necessary?
Sorry for my confusion but I want to get this straight before trying further.

**Comment by edhartnett** [comment]
Independent access is the default.

Both independent and collective (should) work with an unlimited dimension.

I can test this in c when I get a chance.

**Comment by ssgmath** [comment]
@edhartnett thanks for the clarification. Somehow it seems the fortran collective writes (e.g. nf_put_vara_double) seem to work immediately after I create a file (using nf_create_par) without the need for a switch through nf_var_par_access but I cannot manage to then switch back and forth (between independent and collective writes) later - hence my original query regarding the independent write issues with the fortran APIs.

**Comment by edhartnett** [comment]
How do you know that nf_put_vara_double() is writing collectively? I believe it is actually writing independently, because that is the default. However that is not apparent unless a tool like MPE/Jumpshot is used to see what is really happening.

**Comment by edhartnett** [comment]
OK, sorry if this has fallen through the cracks, but GitHub has no good way to elevate an issue so that I see it again and again. ;-)

At the moment, the current netcdf-fortran master with netcdf-c 4.7.0 is passing all parallel tests. Is that the case for you @ssgmath ? Or are you still seeing this failure?

**Comment by ssgmath** [comment]
@edhartnett Perhaps I can try building the latest release of NETCDF-Fortran (to make it build with netcdf-c 4.7.0?) to see of the problem still persists - I shall get back to you if I manage to do this soon(ish) . Thanks.

**Comment by edhartnett** [comment]
OK, also make sure you build netcdf-c with hdf5-1.10.5, which is the latest version of HDF5. An important parallel I/O bug was fixed in HDF5-1.10.4.

**Comment by climbfuji** [comment]
By coincidence, I compiled zlib-1.2.11, szip-2.1.1, hdf5-1.10.5, netcdf-c-4.7.0 and netcdf-fortran-4.4.5 just two days ago on a CentOS 7 platform. The error reported in this issue is gone.

**Comment by ssgmath** [comment]
@climbfuji just to be sure before I try to build my code with your tested specs with netcef-fortran-4. 4.5, did you try a collective write for a variable with unlimited dimension?

**Comment by climbfuji** [comment]
I only ran the tests (./configure, make, make check) and those passed. The error showed up with netcdf-fortran-4.4.4 when running make check.

**Comment by edhartnett** [comment]
Awesome! Keep on netCDFing!
