### ISSUE TITLE
Can't Find NetCDF

### ISSUE THREAD

**Issue by scotty110** [Unidata/netcdf-fortran#441]
New to the project, sorry if this isn't the place for these questions. 
- version: v4.6.1
- Ubuntu on Docker 
- aarch64 / arm
- gfortran-9.5.0

I am trying to build netcdf-fortran but get the following error when I run `cmake -DNetCDF_DIR=/usr/local/netcdf -DCMAKE_INSTALL_PREFIX=/usr/local/netcdf_fortran ..` I get an error 
```
 -- Found netCDF CMake package: netCDF::netcdf 
-- Whether NetCDF-C built with HDF5 enabled: yes 
CMake Error at CMakeLists.txt:668 (message): 
  netcdf-c version 4.7.4 or greater is required 
```
 When I run `nc-config --all` I see that I have version 4.9.2 installed. I only have 1 version of netcdf installed (verified with find), and I added it to my LD_LIBRARY_PATH variable (`/usr/local/netcdf/lib`). 

I looked at [issue](https://github.com/Unidata/netcdf-fortran/issues/299) but that didn't solve my problem. 

[Dockerfile](https://github.com/scotty110/CESM_CAM/blob/cam_3/cam/Dockerfile#L77)

**Comment by WardF** [comment]
Can you attach the `config.log` file generated?

**Comment by scotty110** [comment]
CMake didn't produce a `config.log` so I reverted back to `./configure` (`CPPFLAGS="-I$(nc-config --includedir)" LDFLAGS="-L$(nc-config --libdir)" ./configure --prefix=/usr/local/netcdf-fortran --disable-dependency-tracking`). Which then worked, and I compiled `netcdf-fortran`. 

Sorry for the naive question, I am new to building Fortran and C packages (coming from Python and Golang). Is the `./configure` preferred over `cmake`?  

Thanks so much for your help!

**Comment by WardF** [comment]
Oh, right, thanks, I read right over that.  I think in the Dockerfile you linked, you would need to add `-DCMAKE_PREFIX_PATH=${NetCDF_C_PATH}` to get things to work.  My apologies for missing this detail!

We definitely recommend `cmake` over `autotools` at this point, but both should work, that is on us. Thanks!
