### ISSUE TITLE
using nf_def_grp function with netcdf-fortran-4.2

### ISSUE THREAD

**Issue by tarankalra** [Unidata/netcdf-fortran#47]
Hi, 

I am trying to create groups within a netcdf file while using netcdf-fortran-4.2 installed on my system. 
I was testing the code here that you provided to test the feature from here :

https://github.com/Unidata/netcdf-fortran/blob/master/nf_test/ftst_groups.F 

That generates an error 
This name does not have a type, and must have an explicit type.   [NF_DEF_GRP]
      retval = nf_def_grp(ncid, group_name, grpid)

It seems that the function is not a part of netcdf-fortran-4.2/fortran whereas is present in netcdf-fortran.4.4.1/fortran.

So do you recommend an update to the next version or am I missing something here. 

Thank you for your time,
Taran

**Comment by zerothi** [comment]
That depends on whether netcdf-fortran-4.2 has been installed with netcdf4 support?
Can you check this?

**Comment by tarankalra** [comment]
Yes the base version is netcdf-4.3.2. 
thanks

**Comment by zerothi** [comment]
I think you misunderstood?

4.X is the library version number. NetCDF supports different formats. The documentation of netcdf describes the different formats etc.

In order to use groups netcdf-4.3.2 must be compiled with `--enable-netcdf-4`. If you haven't compiled with NetCDF4 format enabled, then those tests will fail.

**Comment by tarankalra** [comment]
Thanks for clarification. I don't think I used --enable-netcdf-4 while compiling it.

**Comment by tarankalra** [comment]
Hi 
I followed your suggestion and installed netcdf-4.3.2 with netcdf-4 enabled option.
These were the steps -  
----------------------------------------------------------------------------------------------    
1.    sudo ./configure CPPFLAGS='-I/usr/local/hdf5_ifort-1.8.13/include -I/usr/local/zlib_ifort-1.2.8/include' CPPFLAGS='-I/usr/local/hdf5_ifort-1.8.13/include -I/usr/local/zlib_ifort-1.2.8/include' LDFLAGS='-L/usr/local/hdf5_ifort-1.8.13/lib -L/usr/local/zlib_ifort-1.2.8/lib' --prefix=/usr/local/netcdf_ifort_ --enable-netcdf-4_ --disable-dap --disable-large-file-tests --disable-dap-remote-tests
2. sudo make
3. sudo make install

then Installed netcdf-fortran-4.2 again. 
1 ./configure --prefix=/usr/local/netcdf_ifort FC=ifort F90=ifort F77=ifort CC=gcc --enable-shared 2>&1 | tee configure.log
2. make
3. make check
4. make install

**Comment by zerothi** [comment]
Please check these commands:

```
nc-config --all
nf-config --all
```
and check for compiler options, etc.

**Comment by tarankalra** [comment]
Yes, I tried the two commands. I am not quite sure how to interpret the output of these commands. The first one is showing the anaconda's (python) netcdf libraries. The second one points to gfortran compiler, however I have been using the netcdf files with my ifort successfully and it still works after the recent installation that i mentioned above. The only thing is that the --enabled-netcdf-4 option is not working.   

1. nc-config --all

This netCDF 4.3.3.1 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/usr/local/anaconda/include 
  --libs      -> -L/usr/local/anaconda/lib -lnetcdf

  --has-c++   -> no
  --cxx       -> 
  --has-c++4  -> no
  --cxx4      -> 

  --fc        -> 
  --fflags    -> 
  --flibs     -> 
  --has-f90   -> no

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-pnetcdf-> no

  --prefix    -> /usr/local/anaconda
  --includedir-> /usr/local/anaconda/include
  --version   -> netCDF 4.3.3.1

2. This netCDF-Fortran 4.2 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/usr/local/include 
  --libs      -> -L/usr/local/lib  -lnetcdf -lnetcdf 

  --fc        -> gfortran
  --fflags    -> -g -O2 -I/usr/local/include
  --flibs     -> -L/usr/local/lib -lnetcdff  -lnetcdf -lnetcdf 
  --has-f90   -> yes

  --has-nc2   -> yes
  --has-nc4   -> no

  --prefix    -> /usr/local
  --includedir-> /usr/local/include
  --version   -> netCDF-Fortran 4.2

**Comment by zerothi** [comment]
```
nc-config
--has-nc4 -> yes
```
your C-library supports NetCDF4
```
nf-config
--has-nc4 -> no
``` 
your fortran library does not.

You have most likely build it erroneously (probably not provided the hdf5 fortran libraries?).
If you cannot find your original config.log it will be _very_ hard to track the error down, and even then you still need to re-install the fortran libraries...

All we can say is that _something hasn't been done correctly_.

Solutions:
1) Re-install the netcdf-fortran-4.2 going through the debugging process
2) Re-install everything with the updated libraries (both C and Fortran)

Either way should provide a workable solution.

**Comment by tarankalra** [comment]
I did reinstall both netcdf and netcdf-fortran. I do have the config.log as well. 
I am not sure how I can include hdf5 fortran libraries in the installation of netcdf-fortran. Is it the same way as for installing netcdf i.e. to have the hdf5 library path specified during configure such as :  

 sudo ./configure  CPPFLAGS='-I/usr/local/hdf5_ifort-1.8.13/include -I/usr/local/zlib_ifort-1.2.8/include' CPPFLAGS='-I/usr/local/hdf5_ifort-1.8.13/include -I/usr/local/zlib_ifort-1.2.8/include' LDFLAGS='-L/usr/local/hdf5_ifort-1.8.13/lib -L/usr/local/zlib_ifort-1.2.8/lib' --prefix=/usr/local/netcdf_ifort FC=ifort F90=ifort F77=ifort CC=gcc --enable-shared 2>&1 | tee configure.log

I can re-install both netcdf and netcdf-fortran again after I know the way to include hdf5 fortran for netcdf-fortran

**Comment by russrew** [comment]
Taran,

The installation instructions for netCDF-Fortran are [here](http://www.unidata.ucar.edu/software/netcdf/docs/building_netcdf_fortran.html). They explain that if you build with shared libraries, you don't need to specify for netCDF Fortran where the HDF5 library is installed, because the netCDF-C library has the locations of libraries with which it was built. You don't need the HDF5 fortran library, because it's not used by the netCDF Fortran library. A netCDF-4 Fortran function calls netCDF-4 C functions, which call HDF5 C functions.

**Comment by zerothi** [comment]
Ah, yes of course. Sorry for the hdf5 fortran blurp. Something else must be
wrong.
