### ISSUE TITLE
Make Check Issue

### ISSUE THREAD

**Issue by jv2575** [Unidata/netcdf-fortran#49]
Hello,
I am running into the following error when running a make check. Please note this is for netcdf-fortran-4.4.3:

$ make check
Making check in fortran
make[1]: Entering directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/fortran'
make  check-am
make[2]: Entering directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/fortran'
make[2]: Nothing to be done for `check-am'.
make[2]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/fortran'
make[1]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/fortran'
Making check in nf_test
make[1]: Entering directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/nf_test'
make  nf_test tst_f77_v2 ftst_vars ftst_vars2 ftst_vars3 ftst_vars4 ftst_vars5 ftst_vars6 ftst_types ftst_types2 ftst_types3 ftst_groups ftst_path ftst_rengrps f90tst_vars tst_types tst_types2 f90tst_vars_vlen tst_f90_nc4 f90tst_grps f90tst_fill f90tst_fill2 f90tst_vars3 f90tst_vars4 f90tst_vars2 f90tst_path f90tst_rengrps ftst_v2    ftest tst_f90
make[2]: Entering directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/nf_test'
/bin/sh ../libtool  --tag=F77   --mode=link ifort -I../fortran   -I../fortran -g   -o nf_test f03lib_f_interfaces.o test_get.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o ../fortran/libnetcdff.la -lnetcdf 
libtool: link: ifort -I../fortran -I../fortran -g -o .libs/nf_test f03lib_f_interfaces.o test_get.o test_put.o nf_error.o nf_test.o test_read.o test_write.o util.o f03lib.o  ../fortran/.libs/libnetcdff.so -lnetcdf -Wl,-rpath -Wl,/u/3/j/jv2575/netcdf-fortran-intel/lib
../fortran/.libs/libnetcdff.so: undefined reference to `nc_inq_path'
make[2]: *** [nf_test] Error 1
make[2]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/nf_test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-fortran-4.4.3/nf_test'
make: *** [check-recursive] Error 1

**Comment by jv2575** [comment]
Can you please assist me in understanding and resolving this error? I was able to build the cxx tar ball without any issues. Thanks for the assistance.

**Comment by WardF** [comment]
Which version of netcdf-c do you have installed?, and what directory is it installed in?

**Comment by jv2575** [comment]
I didn't install netcdf-c. I just built and did a make check and did not run into any errors. All os this was done within my home directory. I was hoping to have similar results with netcdf-fortran. I hope this information helps.

**Comment by WardF** [comment]
netcdf-fortran requires netcdf-c to build properly; it appears to be complaining about a lack of a symbol provided by netcdf-c.  Can you provide the config.log file generated when you configured netcdf-fortran?  My guess is that there is an older netcdf library installed on the system that does not provide `nc_inq_path`, that netcdf-fortran is finding, instead of the more current version you've built.

**Comment by jv2575** [comment]
Here is the config.log.
[config.log.zip](https://github.com/Unidata/netcdf-fortran/files/237058/config.log.zip)

**Comment by WardF** [comment]
Thanks for providing the file.  From the config.log file, I can see that it is failing to find libnetcdf.  This *should* be a fatal error, I will look into that.  It is finding a `netcdf.h` file, however, which supports the conclusion that there is (or was) an older netcdf-c library installed on this system.

For now, you need to either run `make install` to install `libnetcdf` into a system location, or use `CFLAGS`, `LDFLAGS`, `LD_LIBRARY_PATH` to tell `configure` where to find the netcdf-c library.

**Comment by jv2575** [comment]
I will follow these instructions and let you know should I run into any further issues. I appreciate this info.

**Comment by jv2575** [comment]
Hello,
I am now running into an error when trying to make netcfd-c:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../oc2 -g -O2 -MT libnetcdf4_la-nc4file.lo -MD -MP -MF .deps/libnetcdf4_la-nc4file.Tpo -c nc4file.c  -fPIC -DPIC -o .libs/libnetcdf4_la-nc4file.o
nc4file.c: In function ‘nc4_open_file’:
nc4file.c:2286: error: ‘H5LT_FILE_IMAGE_DONT_COPY’ undeclared (first use in this function)
nc4file.c:2286: error: (Each undeclared identifier is reported only once
nc4file.c:2286: error: for each function it appears in.)
nc4file.c:2286: error: ‘H5LT_FILE_IMAGE_DONT_RELEASE’ undeclared (first use in this function)
make[2]: *** [libnetcdf4_la-nc4file.lo] Error 1
make[2]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-4.4.0/libsrc4'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/hmt/sirius1/skv0/u/3/j/jv2575/netcdf-4.4.0'
make: *** [all] Error 2

Is this something you can help me with?

**Comment by WardF** [comment]
Can you provide the config.log file? This is an HDF5 related issue. NetCDF requires hdf5 1.8.9-1.8.16; what version are you using?

**Comment by jv2575** [comment]
Hello,
Well that would make sense then. I am using 1.8.5 within my environment. I will upgrade this component and let you know the results. Thanks again.

**Comment by jv2575** [comment]
Hello,
I was able to compile everything properly. I really do appreciate your assistance here. I build and compiled the packages in this order:
hdf5
netcdf-c
netcdf-fortran

Thanks again!

**Comment by WardF** [comment]
No problem, glad you were able to resolve this!
