### ISSUE TITLE
Unable to build NetCDF-Fortran with NAG

### ISSUE THREAD

**Issue by adamjstewart** [Unidata/netcdf-fortran#55]
I'm trying to build the latest release of NetCDF Fortran with the NAG Fortran compiler, but it is crashing during `make`. The error message I'm receiving looks like:
```
Warning: nf_control.F90, line 235: Unused local variable INULL
nf_control.F90: In function ‘nf_open_mem_’:
nf_control.F90:310: error: ‘memory_INFO’ undeclared (first use in this function)
nf_control.F90:310: error: (Each undeclared identifier is reported only once
nf_control.F90:310: error: for each function it appears in.)
```
I can provide the rest of the build output or `config.log` if you want it. If you don't have access to NAG for testing, I'm willing to test things on my end.

**Comment by WardF** [comment]
Looking at the lines reported by NAG (310), I'm not seeing any call to a `memory_INFO` function, so I am a bit puzzled by this.  What happens if you try to build from `master` instead of `v4.4.4` ?

**Comment by adamjstewart** [comment]
@WardF This may be a dumb question, but how do I generate `configure` from `master`? Running the following gives me:
```
$ autoreconf -i -f
configure.ac:127: installing './compile'
configure.ac:25: installing './config.guess'
configure.ac:25: installing './config.sub'
configure.ac:31: installing './install-sh'
configure.ac:31: installing './missing'
parallel-tests: installing './test-driver'
fortran/Makefile.am:191: error: Libtool library used but 'LIBTOOL' is undefined
fortran/Makefile.am:191:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
fortran/Makefile.am:191:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
fortran/Makefile.am:191:   If 'LT_INIT' is in 'configure.ac', make sure
fortran/Makefile.am:191:   its definition is in aclocal's search path.
fortran/Makefile.am: installing './depcomp'
libsrc/Makefile.am:11: error: Libtool library used but 'LIBTOOL' is undefined
libsrc/Makefile.am:11:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libsrc/Makefile.am:11:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libsrc/Makefile.am:11:   If 'LT_INIT' is in 'configure.ac', make sure
libsrc/Makefile.am:11:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
```

**Comment by DennisHeimbigner** [comment]
Sometimes you have to prime the pump by running the 'libtoolize' command
and then re-run autoreconf.

**Comment by adamjstewart** [comment]
This gives me a different error message:
```
$ libtoolize
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
$ autoreconf
configure.ac:127: error: required file './compile' not found
configure.ac:127:   'automake --add-missing' can install 'compile'
configure.ac:25: error: required file './config.guess' not found
configure.ac:25:   'automake --add-missing' can install 'config.guess'
configure.ac:25: error: required file './config.sub' not found
configure.ac:25:   'automake --add-missing' can install 'config.sub'
configure.ac:31: error: required file './install-sh' not found
configure.ac:31:   'automake --add-missing' can install 'install-sh'
configure.ac:31: error: required file './missing' not found
configure.ac:31:   'automake --add-missing' can install 'missing'
parallel-tests: error: required file './test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
fortran/Makefile.am: error: required file './depcomp' not found
fortran/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1
```

**Comment by adamjstewart** [comment]
Nevermind, `libtoolize && autoreconf -i -f` worked. Building now...

**Comment by adamjstewart** [comment]
Ok, on `master`, I'm still seeing the same error message:
```
Warning: nf_control.F90, line 235: Unused local variable INULL
nf_control.F90: In function ‘nf_open_mem_’:
nf_control.F90:310: error: ‘memory_INFO’ undeclared (first use in this function)
nf_control.F90:310: error: (Each undeclared identifier is reported only once
nf_control.F90:310: error: for each function it appears in.)
```
Line 310 looks like this for me:
```
cmemoryptr = C_LOC(memory)
```
Let me know if you want the rest of the build output or `config.log`

**Comment by WardF** [comment]
Ok, thanks.  I'm not a fortran developer but I will try to see if I can figure out where this is coming from.  I don't have access to the NAG compiler, but will pass along any ideas I have.  I presume this issue isn't present in v4.4.3?

**Comment by adamjstewart** [comment]
I've never tried `4.4.3` but I can. I suspect no version of NetCDF builds with NAG. It's fairly strict as far as compilers go, and since it isn't open source most developers don't develop against it. Don't feel bad; I have tickets open with OpenMPI, HDF4, and HDF5 which all have problems building with NAG.

**Comment by adamjstewart** [comment]
Just checked and `4.4.3` has a completely different problem:
```
nf_var1io.F90: In function ‘nf_put_var1_’:
nf_var1io.F90:356: error: ‘values_INFO’ undeclared (first use in this function)
nf_var1io.F90:356: error: (Each undeclared identifier is reported only once
nf_var1io.F90:356: error: for each function it appears in.)
```
I'll update the Issue title to be less specific.

**Comment by WardF** [comment]
Yeah, it does appear to be an issue with NAG compiler.  If you're able to figure out what the issue is and provide some insight/a pull request that fixes it, we'll be happy to incorporate it!

**Comment by adamjstewart** [comment]
Ok, I contacted the NAG compiler support team to see if they can debug this. In the meantime, are there any Fortran developers at Unidata that can help? Is there a separate support ticketing system I should go through?

**Comment by WardF** [comment]
Hi Adam, Unfortunately no.  With the retirement of Russ Rew, we lost most of our Fortran expertise.  I'm coming up to speed as I can, but it is hard to replicate his 40 years experience (as you can imagine).

**Comment by adamjstewart** [comment]
No worries, I understand. If NAG compiler support comes up with any patches or suggestions I'll let you know!
