### ISSUE TITLE
ppc64le: configure: cannot compute sizeof (off_t)

### ISSUE THREAD

**Issue by jlost** [Unidata/netcdf-fortran#59]
Hi, I'm trying to compile netcdf-fortran on a POWER8 system. When I try to configure with either FC=gfortran or FC=xlf as my compiler, I get the following error: 

```
checking for off_t... yes
checking for ssize_t... yes
checking for ptrdiff_t... yes
checking for uchar... no
checking for longlong... no
checking whether char is unsigned... yes
checking size of short... 0
checking size of int... 0
checking size of long... 0
checking size of float... 0
checking size of double... 0
checking size of off_t... configure: error: in `/home/u0017592/projects/netcdf-fortran':
configure: error: cannot compute sizeof (off_t)
See `config.log' for more details
```
[Full config.log](https://github.com/Unidata/netcdf-fortran/files/720455/config.txt)

Any thoughts?

**Comment by WardF** [comment]
The issue in the config.log is as follows:

    ./conftest: error while loading shared libraries: libnetcdf.so.11: cannot open shared object file: No such file or directory

This suggests that your libnetcdf.so.11 file is not on the `LD_LIBRARY_PATH`, since the test program *compiles* fine, and only fails at *runtime*.  I would update LD_LIBRARY_PATH to reflect the location of the netCDF-C library and then re-run configure.

**Comment by jlost** [comment]
Thanks, I was able to get it configured by making sure netcdf was being found.

**Comment by WardF** [comment]
Glad you got it working!
