### ISSUE TITLE
Missing Fortran test dependency in CMake build

### ISSUE THREAD

**Issue by zbeekman** [Unidata/netcdf-fortran#63]
Hi,

I'm planning on submitting a pull request with a fix quite soon... feel free to accept the PR, or just make the change yourself.

I was compiling using CMake and the Fortran bootstrap procedure on a KNL machine with GCC/GFortran 6.4 and CMake 3.8.2 and ran into a problem: One of the tests failed to compile because it `use`d a module and the source file was not included in the source list for the test itself.

**Comment by WardF** [comment]
Thanks!  After the upcoming C release, I intend to get the Fortran and C++ libraries squared away with a new version. This is a great help!

**Comment by zbeekman** [comment]
OK... it appears that perhaps there's something strange happening with the bootstrap-fortran procedure... It appears the bug I am referencing was fixed in e1fbffaf7ee1af8552f9e2d88668d72670fbb1c1, a long long time ago. But when building [netCDF-C-4.4.1.1](https://github.com/Unidata/netcdf-c/releases/tag/v4.4.1.1) with CMake and using the Fortran bootstrap method, it must be grabbing an older version of netCDF-Fortran.

**Comment by zbeekman** [comment]
P.S. If I have time to investigate further (not likely at the moment) I'll look into the bootstrap logic, and se what gives and why such an old version of netcdf Fortran got downloaded... likely this is a deficiency in the CMake script for netCDF-C that does the bootstrapping... maybe it points to an old release of netCDF-Fortran and needs updating?

**Comment by WardF** [comment]
I didn't know anybody was using the bootstrap version, you are likely correct!  I will update this.

**Comment by zbeekman** [comment]
The CMake Fortran bootstrap option is featured rather prominently in the ["Getting NetCDF" section of the documentation](https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html#getting). To be fair it does say that it is __Highly Experimental__

**Comment by zbeekman** [comment]
Also quick question about naming: CMake seems to be very case sensitive. `find_package(netCDF)` is different than `find_package(NetCDF)` and the website header (shows up on my tab bar) says "NetCDF" whereas it seems most stuff uses an installation name like "netCDF". Additionally someone [wrote a FindNetCDF.cmake](https://github.com/jedbrown/cmake-modules/blob/72eed2d50acc6d265d3832da8570dfaedc34f0ec/FindNetCDF.cmake) modules, which assumes cmake package configuration files named `NetCDFConfig.cmake` whereas you provide `netCDFConfig.cmake`. Throw GNU Modules into the mix and it becomes very hard to use a canonical CMake `find_package` to find and link against netCDF.
