### ISSUE TITLE
Specify minimum required netcdf-c version for netcdf-fortran releases

### ISSUE THREAD

**Issue by letmaik** [Unidata/netcdf-fortran#68]
Sometimes netcdf-c comes from the package manager but netcdf-fortran is installed manually. It would be helpful to know which netcdf-c version a specific netcdf-fortran requires at least.

**Comment by WardF** [comment]
The latest netcdf-fortran requires netcdf-c 4.4.1.1 or later.  I will look at enforcing a minimum-required version in the fortran and C++ interfaces to the C library.
