### ISSUE TITLE
Non-standard OSX configuration 

### ISSUE THREAD

**Issue by lipnikov** [Unidata/netcdf-fortran#70]
I am using custom mpicc to build the NetCDF-Fortran library, version 4.4.4. The gcc compiler is provided by MacPorts. The following error appears during the build stage:

 gcc-mp-6: error: unrecognized command line option '-fmacro-backtrace-limit=0'

The library is build if I remove this option by commenting out line 486 in CMakeList.txt. I noticed no compilation issues when mpicc was build using the LLVM compiler.  One solution is to set up fmacro-backtrace-limit flag only for the LLVM compiler...

**Comment by jedwards4b** [comment]
I found this same problem installing from homebrew with netcdf-fortran-4.4.4.tar.gz
