### ISSUE TITLE
Doxygen version of the documentation

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#75]
Fortran needs a documentation update.

**Comment by edhartnett** [comment]
@WardF can you update the documentation on-line so I can close this ticket? Thanks!

**Comment by WardF** [comment]
I need to get the web devs to make the appropriate server-side changes for formatting, but that should come shortly.  The current documentation is available at https://www.unidata.ucar.edu/software/netcdf/fortran/docs, and is linked from the front page of the C documentation.  Thanks!

**Comment by edhartnett** [comment]
Great, thanks!
