### ISSUE TITLE
f03tst_open_mem fails against current netcdf-c master, works with v4.6.1

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-fortran#82]
Seeing a failure in `f03tst_open_mem` against the current `master` branch of netCDF-C.  

Error details here: http://cdash.unidata.ucar.edu/testDetails.php?test=101729&build=2490

Output from test is as follows:

````
Test output
 
 *** Testing fill values.
 
  testing nf_open_mem
 
 
  FILE = f03tst_open_mem.nc is         6398  bytes
 
STOP 41
````

**Comment by DennisHeimbigner** [comment]
I was able to recreate this using C-code only, so at least it is not a fortran problem.

**Comment by WardF** [comment]
Ah, so it's an actual bug and not just a fortran test that needs to be updated?  That is good to know, and also a bit surprising our existing C tests didn't catch this.  Should I open an issue at netcdf-c?

**Comment by DennisHeimbigner** [comment]
It is odd. I have another test that seems on the surface to be
identical, but works fine.

**Comment by DennisHeimbigner** [comment]
It appears that the failure only occurs when using hdf5 1.10. With 1.8.20, it seems to work.

**Comment by WardF** [comment]
Interesting. Any specific version of 1.10?

**Comment by DennisHeimbigner** [comment]
I am using 1.10.1; no idea if other versions fail.

**Comment by WardF** [comment]
Is this a bug we can catch (error code being returned) or is this a legit bug in HDF that we can report? Also, if you have a test that does essentially the same thing but works, is there a workaround we can do?

**Comment by WardF** [comment]
Is it possible to get the C test you created that also fails?

**Comment by DennisHeimbigner** [comment]
Attached. There is the .c program plus the .nc file it attempts to open.
[openmem.zip](https://github.com/Unidata/netcdf-fortran/files/2037160/openmem.zip)

**Comment by DennisHeimbigner** [comment]
Attached. There is the .c program plus the .nc file it attempts to open.
[Uploading openmem.zip…]()

**Comment by DennisHeimbigner** [comment]
>Is this a bug we can catch (error code being returned) or is this a legit bug in HDF
>that we can report?
Not sure yet.
> Also, if you have a test that does essentially the same thing but works,
I think I spoke too soon. Now the other test fails also.

**Comment by DennisHeimbigner** [comment]
Fixed by pr https://github.com/Unidata/netcdf-c/pull/1008
