### ISSUE TITLE
Suggest build simplification, require fortran 03...

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-fortran#85]
Currently the netcdf-fortran build supports both fortran 03 and fortran 77 builds.

Really, there's no need to continue supporting the non-03 builds. Fortran 03 is widespread. No science users need to be stuck with a fortran 77 compiler any more.

SIgnificant simplification of the code and build is possible by removing this legacy support, which would hopefully help make netcdf-fortran more agile and easier to maintain and improve.

**Comment by DennisHeimbigner** [comment]
I agree, but note that I got a Fortran 77 test case from a user just recently (within the last
two months).

**Comment by edhartnett** [comment]
Switching to 03 for compiles does not mean we don't support the F77 API. It just means we require a Fortran 03 compiler to compile the F77 API.

This is reasonable, as compilers are all updated, but there may well be lots of F77 code out there. This code will still work just fine after we move to only 03 builds.

What won't work is building netCDF with g77 instead of gfortran. 

So in netcdf-fortran we can get rid of the cfortran.h stuff and all files associated with it.

**Comment by DennisHeimbigner** [comment]
Ok, what you said originally was ambigous.
