### ISSUE TITLE
Problem with NAG compiler due to old version of libtool

### ISSUE THREAD

**Issue by skosukhin** [Unidata/netcdf-fortran#94]
Hello.

Is it possible to use a more recent version of Libtool for the release tarballs?

The one being used now (2.4.2) does not "know" enough about NAG compiler. Libtool 2.4.6 works better. There are other useful improvements in the newer version probably.

Thanks.

**Comment by WardF** [comment]
When we create the upcoming release, we'll use the latest libtool available; using the latest version of Ubuntu, we should be able to use libtool 2.4.6+.

**Comment by wadudmiah** [comment]
Is there a workaround to building netcdf using the NAG Fortran compiler?

**Comment by skosukhin** [comment]
@wadudmiah if you need to build version 4.4.4 and older, you can apply the following patch:
```patch
diff --git a/configure b/configure
index 06ac8b0..d518a1a 100755
--- a/configure
+++ b/configure
@@ -10657,6 +10657,8 @@ _LT_EOF
        lf95*)                          # Lahey Fortran 8.1
          whole_archive_flag_spec=
          tmp_sharedflag='--shared' ;;
+       nagfor*)
+         tmp_sharedflag='-Wl,-shared' ;;
        xl[cC]* | bgxl[cC]* | mpixl[cC]*) # IBM XL C 8.0 on PPC (deal with xlf below)
          tmp_sharedflag='-qmkshrobj'
          tmp_addflag= ;;
@@ -14252,6 +14254,8 @@ _LT_EOF
        lf95*)                          # Lahey Fortran 8.1
          whole_archive_flag_spec_F77=
          tmp_sharedflag='--shared' ;;
+       nagfor*)
+         tmp_sharedflag='-Wl,-shared' ;;
        xl[cC]* | bgxl[cC]* | mpixl[cC]*) # IBM XL C 8.0 on PPC (deal with xlf below)
          tmp_sharedflag='-qmkshrobj'
          tmp_addflag= ;;
@@ -17142,6 +17146,8 @@ _LT_EOF
        lf95*)                          # Lahey Fortran 8.1
          whole_archive_flag_spec_FC=
          tmp_sharedflag='--shared' ;;
+       nagfor*)
+         tmp_sharedflag='-Wl,-shared' ;;
        xl[cC]* | bgxl[cC]* | mpixl[cC]*) # IBM XL C 8.0 on PPC (deal with xlf below)
          tmp_sharedflag='-qmkshrobj'
          tmp_addflag= ;;
```
As far as I understand, version 4.4.5 does not have this problem anymore, since its configure script is generated with a more recent version of libtool.

**Comment by wadudmiah** [comment]
@skosukhin thanks!

**Comment by WardF** [comment]
Is it safe to consider this issue resolved with the release of 4.4.5?

**Comment by wadudmiah** [comment]
Yes, you can close this as resolved.

**Comment by WardF** [comment]
Great, thank you!
